### ISSUE TITLE
iOS Captive Portal Fail workaround

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#100]
when connecting to a captive portal iOS devices try to grab http://apple.com/library/test/success.html
if they can't they prevent the user from accessing anything over the network due to the assumption that they need to login to the captive portal still.
the reported fix (via Benn) is to place a copy of success.html in the same location but on the captive portal webroot.
success.html is a highly complex system where by the following data is returned for verification by the device.

```
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN"> 
 <HTML> 
 <HEAD> 
      <TITLE>Success</TITLE> 
 </HEAD> 
 <BODY> 
      Success
 </BODY> 
 </HTML>
```

although i expect that it just wants to see the 200 response and the html is just to give some content with the response.
the action required is to place a copy of success.html in library/test/success.html in the captiveportal's webroot.

**Comment by haxwithaxe** [comment]
confirmed that this happens. still not sure if the fix suggested works or not.

**Comment by virtadpt** [comment]
I think that iOS is looking for the full URI.  We're already grabbing apple.com with dnsmasq (which is spoofing the set of all possible Internet domain names).

iOS captive portal anti-fail commited as be536f6337c63b6a98a15c6f47e48b28e8d0ada8.

**Comment by virtadpt** [comment]
Figured out how to make it work.  Fix commited in 5191f6e81f926269dfe81d5deffd1ae0687595ae.

Internally, CherryPy converts periods in URIs it serves into underscores before mapping components of the URI to methods.  I changed CaptivePortalDetector.success() to .success_html() and it started working.

**Comment by virtadpt** [comment]
iOS7 completely b0rked captive portal detection and interaction.  Re-opening because a) we have notes and stuff to add as comments, and b) we need to fix this.

**Comment by virtadpt** [comment]
Closing because this is an entirely separate implementation of the problem, and involves an entirely separate solution.
