### ISSUE TITLE
Minimize in-built ability to use a node for surveillance.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#105]
Porteus Linux (and, by extension, Byzantium Linux) include by default some utilities that can be used by malicious parties to perform surveillance on a mesh the node is a part of.  This includes libpcap and tcpdump and probably a couple of other things.  I propose that we go through the list of packages and either remove or disable utilities that could be abused to illicitly monitor traffic.  We could unpack the core .xzm files, delete some of them, and then re-pack the core files.  Alternatively, we could also add to the 000-byzantium.xzm module a bunch of 0 length files that effectively overwrite the files as they are currently presented to userspace; to re-expose them would mean unmounting 000-byzantium.xzm, which pretty much kills the usefulness of the node.

This comes after reading the proceedings of a recent conference panel in which manufacturers of telecommunications hardware defended the inclusion of mass surveillance capabilities in their products under the guise of 'lawful intercept' which are known to be widely abused.  It's the "We don't drop the bomb, we just built it" argument, and regardless of the rhetoric the proof of the pudding is in the eating.  Or, in this case, the dissidents around the world who are being monitored and sometimes blackmailed out of their activities using information gathered with these subsystems.

Let's not make it any easier for them to abuse our work than we have to, is all I'm saying.

Canonical list of Slackware packages that are part of Porteus Linux by default: https://porteus.org/component/content/article/57-general-information/126-package-list-for-v-10.html

**Comment by Sitwon** [comment]
I actually come up on a different side of this argument. I say leave them in. Tools like libpcap/tcpdump are well-known enough that any would-be surveillor who knew how to use such tools would also know how to download and install them. And anyone who can't download and install them probably wouldn't know how to use them with any effectiveness anyways.

Furthermore, these tools happen to be very valuable network debugging and diagnostic utilities, as was their original design purpose. Let's be clear, we're not talking about metasploit or dniff or middler or other tools that were explicitly designed for attack. We're talking about a pair of tools that legitimate network engineers and admins rely on every day to troubleshoot issues. I think removing them is as questionable as thinking that removing GCC will enhance security. On Linux, there's often more than one way to skin a cat. For example, you could also use Netfilter to capture and log packets, should we remove iptables as well? Should we remove route to prevent them from creating and advertising false routes?

Trying to hide these these commonly available tools smacks of obfuscation which is a poor approach to security. It would hurt the legitimate users by depriving them of valuable tools, while hardly presenting a bump in the road to attackers sophisticated enough to use them.

Furthermore, it has been suggested to me that Byzantium itself falls into the category of tools that could be used for good or evil. While we intended for Byzantium to be used by "the good guys", how do we know which side is the good guys? Tools that help individuals evade censorship could also help criminals or terrorists evade law enforcement.

Every useful tool could become a weapon in the wrong hands.

I don't think that obfuscating administrative utilities is the way to ensure privacy and security. Instead we need to educate users on strong cryptography and make it as easy as possible for them to use it by default.
