### ISSUE TITLE
ad-hoc on osx

### ISSUE THREAD

**Issue by ag4ve** [Byzantium/Byzantium#109]
it's a pita to join an ad-hoc network on osx. once joined, packets weren't routable (i assume i needed to manually add a route? - need to test / figure this out). something needs to be done to simplify / streamline this process. as most wireless network cards won't do promiscuous mode (and idk whether that would allow simultaneous ad-hoc and infrastructure anyway) and i don't know of another way to simplify joining a network in osx, i'm at a loss as to the best way to resolve this.

**Comment by haxwithaxe** [comment]
you shouldn't need promic mode. the network is an adhoc network with the mesh part layered on top of it. without babeld you can connect to a byzantium node with plain dhcp. there is a captive portal though so everything will be dropped until you go through that if the version of byzantium you are using has that avaiable/enabled.

**Comment by virtadpt** [comment]
The problem is that OSX was setting up ag4ve's laptop as an ad-hoc node, but not an ad-hoc client.  It wasn't running dhcpcd to get its configuration information from our Byzantium node.

There has to be a trick to it.

**Comment by haxwithaxe** [comment]
open the terminal and type "sudo dhcpcd" ?

On Mon, Apr 30, 2012 at 2:01 PM, The Doctor
reply@reply.github.com
wrote:

**Comment by haxwithaxe** [comment]
or let the mac users get eaten by zombies?

**Comment by ag4ve** [comment]
If that's the only solution than that'll have to be it. However, I am
hoping there's a better one.

It did eventually get an IP (not sure how much fiddling I had done at that
point). Either way, I'm hoping we can make non byzantium clients work out
of the box with the mesh as well as they do with other networks. <-- is
really the point of this ticket.
On Apr 30, 2012 2:45 PM, "haxwithaxe" <
reply@reply.github.com>
wrote:

**Comment by virtadpt** [comment]
@haxwithaxe That didn't work.

On a Linux machine, we'd use the command `iwconfig wlan0 mode ad-hoc` to put the chipset in ad-hoc mode.  That doesn't seem to be possible in OSX.  The instructions we found seem to be for configuring OSX to run as an ad-hoc node.  It is my suspicion that it sets up a dhcp server in that capacity.  This is not what we need.

**Comment by virtadpt** [comment]
For future reference, here are instructions for joining iProducts to ad-hoc networks (from here: http://forums.macrumors.com/showthread.php?t=737424)

1) Set up the ad hoc network on the mac/PC
2) Go to settings on the iphone and enable flight mode
3) Go to wifi on the iphone (in settings) while still in flight mode and select the ad hoc network
4) Wait 20 seconds and next to the plane in the top right corner of the screen a wifi symbol will appear (still on the iphone)
5) You're good to go.

**Comment by virtadpt** [comment]
@ag4ve When you got your Mac on the Byzantium mesh, do you recall what IP address your laptop had?  It'll help us determine if it got its network configuration information via DHCP from the Byzantium node, or if your Mac picked a 169.254/16 (in which case, we need to add some code to make it possible for APIPA clients to function on a mesh in the same way that Ubuntu does).

**Comment by virtadpt** [comment]
Instructions for kicking MacOSX into ad-hoc mode: http://www.wi-fiplanet.com/tutorials/article.php/3822651/How-to-Create-an-Ad-Hoc-Network-Part-2.htm

X-factors:
- Does this make it possible for the Mac in question to inter-operate with an existing ad-hoc wireless net?
- Does it configure itself using DHCP or APIPA?
- How reliable is it (c.f., ticket #91)?
- What (if anything) would we have to add to Byzantium to toggle the It Just Works(tm) bit?

**Comment by ag4ve** [comment]
iirc, it got a 10.../24 address (or maybe it was 192 - either way, it
was legit). i could ping you but not route anywhere (obvious why given
#108 iirc)

On Mon, Apr 30, 2012 at 17:27, The Doctor
reply@reply.github.com
wrote:

**Comment by virtadpt** [comment]
Okay, if it got a 10/24 then your Mac got its configuration information from the mesh node.  That's correct.

Also, it is probably becase the IP tables rules for NAT weren't installed because I configured the gateway manually.

**Comment by jjerrodtaylor** [comment]
I downloaded your alpha release and I really haven't found any clear instructions on how to install things on a mac. I've found instructions for Linux and even windows. Apple can't get any love?

**Comment by ag4ve** [comment]
@jjerrodtaylor so, i'm not sure how to install (any) linux on osx. that said i see two problems here, first our documentation is lacking at this point, and i'm not sure how many people would like to run pure byzantium on apple hardware.

side note - i have found osx to be lacking in many aspects of what i'd like a unix system to be. however, i will continue to run osx on a mac for the support (paid and community) and run other os's within a vm for functionality (as i would with windows).

ps - now that i have something productive for this thread, i'll ps with this - may @haxwithaxe wake up with an apple burned into his iris.

**Comment by virtadpt** [comment]
We need three things right now: Serious testing of v0.1a or v0.2a-RC1 on Apple hardware, documentation of how to boot a live distro from CD or USB on a Mac, and written up test results.  I tried to get my hands on a couple of older Mac laptops but they were all spare parts (i.e., broken and offered for cannibalization) and so weren't worth it.

**Comment by ag4ve** [comment]
well, i guess i can shut down my mbp and make a writeup...

<gripe>
it's sorta bad that the only thing i can't save are things in my
terminal - tabs and scroll back. chrome takes care of most of the rest
of my stuff, but the terminal not saving state on a reboot has always
given me fits.
</gripe>

On Fri, May 25, 2012 at 4:45 PM, The Doctor
reply@reply.github.com
wrote:

**Comment by jjerrodtaylor** [comment]
I have two macs. I read over the setup instructions and there were no directions for mac. I even tried going through the windows setup instructions and the linux instructions but they didn't work. I still need to try setting it up on a flash drive though.

By the way, I live in the D.C. area and have even by HacDC in Columbia Heights.

**Comment by virtadpt** [comment]
There are no setup instructions for Mac because we don't have any to test on.  It's something we need to figure out.  Try booting it from flash drive, that's what we do.

Excellent!  Stop by for a dev.sprint!

**Comment by jjerrodtaylor** [comment]
Well I'll bring two to the next dev sprint.

**Comment by virtadpt** [comment]
Great - thank you!

**Comment by jjerrodtaylor** [comment]
Speaking of dev sprints, when is the next one? I didn't see a date on the wiki or the HacDC site.

**Comment by virtadpt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 05/31/2012 09:58 AM, Jamaal Taylor wrote:

> Speaking of dev sprints, when is the next one? I didn't see a date 
> on the wiki or the HacDC site.

The HacDC calendar says that it starts Friday night (29 June 2012).

---

The Doctor [412/724/301/703] [ZS]

PGP: 0x807B17C1 / 7960 1CDC 85C9 0B63 8D9F  DD89 3BD8 FF2B 807B 17C1
WWW: https://drwho.virtadpt.net/

"Reality is not only stranger than we suppose, it's stranger than we
can suppose." --Terrence McKenna

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.19 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iEYEARECAAYFAk/HnmYACgkQO9j/K4B7F8F0EACbBrRf9VUZy/mWwR3oKpxh4WdR
W9sAoIMlIOrkJkc/XRkPPkdbiHY4KvhN
=DA/I
-----END PGP SIGNATURE-----

**Comment by virtadpt** [comment]
We need to revisit this with a couple of Macs.

**Comment by virtadpt** [comment]
Attn Mac users - we need people testing release candidates of the v0.3.2a .iso image - that's our Mac port of Byzantium!

**Comment by haxwithaxe** [comment]
depends #195

**Comment by haxwithaxe** [comment]
works for us
