### ISSUE TITLE
Fix CSS in control panel.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#112]
When I started reworking Status() to make it more useful I somehow managed to break the CSS.  I think it's because I changed everything up and now the CSS doesn't match the HTML generated by the object anymore.

**Comment by virtadpt** [comment]
Watching the output of the control panel, the .css files are being downloaded by the web browser successfully (HTTP 200).  It's a problem in the HTML and the CSS for sure.

**Comment by virtadpt** [comment]
The problem's in css/reset.css.  I figured this out by commenting out all of the references to .css files in /index.html, reloading the page, and then uncommenting them in reverse order to determine at what point table borders broke.

**Comment by laurelindel** [comment]
Are you talking about the CSS for index.html for the control panel? Because I fixed it at about one am. 

If it still doesn't look right, let me know what's not where or how it needs to be, and I'll get on it ASAP.

**Comment by virtadpt** [comment]
That's what I'm talking about, yes.

I just did a git pull and a git log, and I don't see your changes in there.  Did you do a git push to upload them?

**Comment by laurelindel** [comment]
Hey B -

Last night, the first time I changed the file, it did take - I checked to
make sure - but this morning, it was gone. After re-creating the changes in
the index.html file I tried to get them posted, but they wouldn't. I'm
guessing that this morning, I was doing a commit and not a push. I emailed
you the changed file. I'm hoping that you can post it to github - I can't
access from work.

I've got three questions:
1. When will you be giving your presentation? If it's tomorrow, I'll try
   again to do the push when I get home from work.
2. Are there any other html pages in the control panel folder that you'll
   be using in your presentation? If so, tell me what they are and I will make
   the inline style changes to them this evening.
3. Do the table cells contain the correct content in the correct order?

Love you - good luck - let me know.

-Jan

On Fri, May 11, 2012 at 1:33 PM, The Doctor <
reply@reply.github.com

**Comment by virtadpt** [comment]
Fixed by Laurelindel, commit 2c0e9dc2e3f7739da55feac673434cef332e88d7.
