### ISSUE TITLE
Make captive portal's detection of client browser language more robust.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#117]
There are some browsers out there that don't send well-formed Accept-Language headers to the server (i.e., 'en-US').  They instead send just enough to get the point across but no more ('en').  While brevity is the soul of wit it also shoots string parsing in the stomach with a potato gun.

Rework the code in CaptivePortal.index() to only try to match the contents of that header up to where the dash ('-') would be in the value of the string 'clientlang'.

There is a potential downside here: Language sets that have multiple dialects (cn-cz vs cn-ch).

Reference ticket: #116

**Comment by virtadpt** [comment]
This is tricky.  On one hand, we don't have enough translations of everything to make this worthwhile.  On the other hand it already falls back to English.  We should get a wiki page up for translations.

**Comment by Sitwon** [comment]
Not relevant since we don't have translations anyways and are always returning the English page.
