### ISSUE TITLE
Use copytoram as default boot option

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#118]
By default, we should be using the copytoram cheat code at boot so that the USB drive can be removed after the node is booted.

The downside is that we would lose persistence, so the secondary boot option should be "persistent boot" and not use copytoram.

**Comment by virtadpt** [comment]
Added with commit 001ca126cfb5aa3cd760a23a4db8849be831d2b7.

**Comment by virtadpt** [comment]
This works but it bogs down the boot process like nobody's business.  On Dragonfly it easily tripled the boot time (taking it out of the realm of speedy).  We might want to reconsider defaulting to this, at least for the alpha releases.

**Comment by SpartacusAU** [comment]
Boot times I have for Asus Eee PC 1016P are:

OS                               Media                      Mode                                       Time to boot to desktop

Byzantium   v0.2a         USB 2.0                   Copy2Ram                                2:43
Byzantium   v0.2a         USB 2.0                  Always Fresh                             2:10

Ubuntu 12.04 LTS        SDHC  card               run from USB                            1:30
Win7                        5400 RPM HDD            standard                                   5:38*

*Desktop appears at 3:00 but CPU is at 100% utilization and therefore unusable until 5:38

For this example the extension in boot time is about 20-25% longer with copy2Ram.

Regardless of the time considerations I think the default should be Copy2Ram.

People do stupid things on first boot and highest possible security should be the default for the final version. 
Everyone is a noob the first time.

Perhaps put copy2ram as first option on boot mode list for now?

With code being compressed / pruned/ optimized at later stages the boot should be faster, no?

**Comment by Sitwon** [comment]
It does take substantially longer to boot a CD with copytoram, however without copytoram we have seen race conditions crop up when booting from CD.

The default recommendation will be to use copytoram, but we will keep a boot option w/o copytoram.
