### ISSUE TITLE
Create a VM image version

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#119]
As suggested by someone at CarolinaCon, we should distribute a VMDK image of the Byzantium Linux distro so that people can run it without from within their preferred host OS.

**Comment by virtadpt** [comment]
There is no reason this cannot be done.  The easiest way would be to take one of the development VMs, install all of the software, and delete the repositories (and any cached information for same), leave the VirtualBox guest extensions in place, and then export it.

**Comment by virtadpt** [comment]
One of these days I'll remember to make my test VMs available...

**Comment by ITechGeek81** [comment]
Was the request specific to VMDK's (VMWare) or just VM images?  If it was for VMWare images, I do have a copy of VMWare Workstation that I can create the VM on for you.

**Comment by virtadpt** [comment]
I'm not sure.  It could be either or both.

**Comment by haxwithaxe** [comment]
updates?

**Comment by virtadpt** [comment]
Won't fix - it's trivial to run an ISO image in a VM without persistent storage.
