### ISSUE TITLE
Submit our website to http://www.linuxliveusb.com.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#120]
http://www.linuxliveusb.com is the homepage of Linux Live USB, a utility for Windows that automagically takes .iso images and either installs them to USB keys for you or virtualizes the image so you can test it from inside of Windows.

I think we should test Byzantium Linux with their utility and if it works submit a link to our website to linuxliveusb.com to get us on their Linux Distro Compatibility List.

We might also want to consider bundling their utility in the root directory of our .iso image to make it easier for Windows users to install to a USB key and deploy nodes.

**Comment by haxwithaxe** [comment]
if it hasn't already been done it's worth a shot
