### ISSUE TITLE
Add babelweb to the control panel

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#122]
https://github.com/kerneis/babelweb

Let's add it to the control panel to visualize mesh network connectivity/topology.

**Comment by virtadpt** [comment]
We already have node.js and npm... let's do it.  All it needs is a SlackBuild and it'll be good to go.  When it's in I'll add a link in it to the control panel.

**Comment by Sitwon** [comment]
Seems to be working, now we just need to start it up automatically and link to it.

**Comment by haxwithaxe** [comment]
depreciated?
