### ISSUE TITLE
"SERVER_PROTOCOL" not always http:// (services.py)

### ISSUE THREAD

**Issue by kg6gfq** [Byzantium/Byzantium#125]
services.py lines 77 and 105 use `os.environ['SERVER_PROTOCOL']` to get the http:// (or whatever) for service URLs, but that currently gives links like "HTTP/1.1://localhost:6667/", which doesn't work so well.  

Also, line 89 should look like line 111, since it currently gives URLs with a "/" before the port number.

**Comment by virtadpt** [comment]
Fixed in commits e536ef174409ecbb309e04a7fb8cc7fe8a30491e and e0a15d407d878a56f6a92bd9bc4ca3d3a40da880.
