### ISSUE TITLE
Easy job for any Python coders

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#129]
This should be an easy job for anyone with a little bit of Python experience.

The code for the control_panel is littered with statements like the following:

``` python
if debug:
    print "DEBUG: Some message."
```

Personally, I find that a bit ugly. Ideally it should look more like `log.debug("Some message")` or even just `debug("Some message")`. So your mission, if you choose to accept it, is to either find or write a Pythonic logging framework and integrate it into the control_panel code.

There are plenty of powerful logging frameworks out there for Python, so I'd be fine with simply integrating any of those. However writing a logging framework in Python is  good practice for a beginner. So if anyone wants the learning experience and needs a bit of motivation, here it is.

It's not the most glamorous job, but it is important (and will become increasingly important as we continue to extend the control_panel and need more sophisticated logging).

**Comment by shanel** [comment]
If you are cool with just python's built in logging module (import logging) I just did this and can send you a pull request.

**Comment by Sitwon** [comment]
Please do.

On Sun, Jul 15, 2012 at 12:01 AM, Shane Liebling <
reply@reply.github.com

**Comment by shanel** [comment]
Should this be closed out now?

**Comment by Sitwon** [comment]
It's mostly done, but I think there's still a little bit more we can do. Eg, treating the "if test: print ..." as debug messages.

**Comment by shanel** [comment]
I'm on it.

On Tue, Jul 17, 2012 at 7:31 PM, Ben Mendis
reply@reply.github.com
wrote:

**Comment by Sitwon** [comment]
I believe this one has been solved. Good work @shanel
