### ISSUE TITLE
500 error on /gateways

### ISSUE THREAD

**Issue by hornc** [Byzantium/Byzantium#132]
Using v0.2a-RC/byzantium-0.2a-RC-20120623-1652.iso  on a Dell Lattitude D505 laptop 512 MB RAM 

I am consistently getting an error visiting:  http://localhost:8080/gateways/
  ==>
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/local/sbin/gateways.py", line 67, in index
    self.update_network_interfaces()
  File "/usr/local/sbin/gateways.py", line 203, in update_network_interfaces
    if new_interface in line:
NameError: global name 'new_interface' is not defined

The above error happens all the time.

This may be unrelated, but it seems to take me a few goes to configure the network interfaces, and I do get an error the first time after booting on Configure Mesh Network:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/local/sbin/networkconfiguration.py", line 684, in set_ip
    pidfile = open(str(captive_portal_pidfile), 'r')
IOError: [Errno 2] No such file or directory: 'captive_portal.eth1'

When I re-configure the Network interface though, things seem to work (i.e I can connect other devices to the Byzantium network), although the 'eth1' button is still coloured red under Network Interfaces.

I'm happy to provide further log data if I'm told where to look.
\cheers

**Comment by virtadpt** [comment]
What's the complete filename of the .iso image you booted?

**Comment by hornc** [comment]
The iso file name was:  byzantium-0.2a-RC-20120623-1904.iso

**Comment by virtadpt** [comment]
That's an older RC.  Try this one, we've applied a bunch of fixes to it: http://project-byzantium.org/downloads/v0.2a-RC/byzantium-0.2a-RC-20120627-1540.iso

**Comment by hornc** [comment]
I have just tried byzantium-0.2a-20120627-2142.iso (the most recent iso I found in the downloads folder), and second part of the issue now gives me the more readable error:

WARNING: Unable to open captive portal PID file captive_portal.eth1
WARNING: Unable to open captive portal PID file captive_portal.eth1
Mesh interface eth1 IP configuration: 192.168.23.172/255.255.0.0
Captive portal daemon running, PID: ERROR: captive_portal.py failed, returned code .

The eth1 button is still red, but I can proceed as before. Again, this only happens the first time.

The first part of the issue has been completely resolved, I can view the /gateways page fine now.

**Comment by virtadpt** [comment]
Is eth1 a wireless interface on that box?  What wireless chipset does it have?  Are you trying to start the wireless interface as the gateway in addition to being a mesh interface?

**Comment by hornc** [comment]
eth1 is a wireless interface. lspci output:
01:03.0 Network controller: Intel Corporation PRO/Wireless 2200BG [Calexico2] Network Connection (rev 05)
and I wasn't trying to start the gateway.

I tried on another laptop with more RAM, and get exactly the same message (except the wireless interface is named wlan1) only when I boot up without copy2ram.  When I boot it with copy2ram, there is no error configuring network interfaces. The card on that one is:
03:00.0 Network controller: Intel Corporation Centrino Advanced-N 6200 (rev 35)

The common factor I am seeing is booting without copy2ram. I was hoping to try and do some more investigation, but that might be tomorrow...

**Comment by virtadpt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 06/29/2012 09:41 PM, Charles Horn wrote:

> eth1 is a wireless interface. lspci output: 01:03.0 Network
> controller: Intel Corporation PRO/Wireless 2200BG [Calexico2]
> Network Connection (rev 05) and I wasn't trying to start the
> gateway.

Which RC candidate were you using?  We added firmware for the ipw2200
wireless chipset (we added every firmware package from Slackware's
series N repository incidentally) on Friday night but due to the storm
that hit DC that night couldn't push it to the release candidate
download site until today.

> I tried on another laptop with more RAM, and get exactly the same 
> message (except the wireless interface is named wlan1) only when I 
> boot up without copy2ram.  When I boot it with copy2ram, there is
> no error configuring network interfaces. The card on that one is: 
> 03:00.0 Network controller: Intel Corporation Centrino Advanced-N
> 6200 (rev 35)

Same thing, and same fix.

> The common factor I am seeing is booting without copy2ram. I was 
> hoping to try and do some more investigation, but that might be 
> tomorrow...

Okay.

We're at Sitwon's house fixing this - he has power and space for us to
set up and hack on this.  I've uploaded some new release candidate
images to the primary download site, all of which have the firmware
fixes we made on Friday.  Grab the latest one and try it, and let us
know how it works.

By way of explaining, we went through Slackware-CURRENT on Friday
night (29 June 2012), took every wireless firmware package, converted
them, and added them to Byzantium Linux.  The ipw2200 and iwlwifi-6200
packages were among them.

---

The Doctor [412/724/301/703] [ZS]

PGP: 0x807B17C1 / 7960 1CDC 85C9 0B63 8D9F  DD89 3BD8 FF2B 807B 17C1
WWW: https://drwho.virtadpt.net/

The future belongs to the brave.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.19 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iEYEARECAAYFAk/wscAACgkQO9j/K4B7F8HOQgCg6dZbC0S2V1+frIwIQN/Ii7ti
OwsAn1Fos6B86reJ5idsO62OgqHQ8zeo
=0Q/S
-----END PGP SIGNATURE-----

**Comment by Sitwon** [comment]
This should be re-tested with v0.2a, it's probably related to the race condition(s) we identified when booting from a CD without copy2ram.

**Comment by hornc** [comment]
Hi, sorry I haven't relpied earlier -- 

I retried on both my laptops mentioned above without copy2ram using the
latest v0.2a iso I found from http://project-byzantium.org/downloads/v0.2a-RC/

 byzantium-0.2a-RC-20120706-1425.iso 06-Jul-2012 11:31  460M  

and I still get the error message from commit 2336c50 when I configure the network interfaces for the first time:

Captive portal daemon running, PID: ERROR: captive_portal.py failed, returned code .

(Note: there is no error code in the message I receive, the above is exactly how it appears on the page)

 I tried to delve into this further last night, but it's hard because nothing really seems to be wrong -- I can proceed as normal and set up mesh networking and subsequent attempts to reconfigure the interface no longer give the message.

 I saw the race condition debug line -- maybe that is doing it's thing but displaying an error message anyway? The interface button 'wlan0 / eth1' stays red, but I can't figure out what it is complaining about -- everything seems to work fine.

 So to attempt a summary: I don't think this is a big issue at all -- I still get what seems to be a non-meaningful error message only when booting without copy2ram option and on the FIRST attempt to configure the network interface, but the workaround is to ignore it an proceed as normal with no ill effects that I have noticed. Commit 2336c50 was an improvement in that it no longer looks like something exploded :)  I have no issue with this using copy2ram on the one laptop that handles it.

**Comment by Sitwon** [comment]
Hi Charles, 

I don't think this issue got fixed in v0.2a, but as soon as we get back from NYC this will be at the top of our list for v0.3a. In fact, we're planning an overhaul of the entire control panel to make bugs like this far less likely.

Ben the Pyrate

**Comment by virtadpt** [comment]
We're in the process of overhauling the Python code (vis a vis the captive portal daemon and control panel) so we'll revisit this shortly.  We do know that it's related to the copy2ram race condition (ticket #118).
