### ISSUE TITLE
Firefox Error Console has three errors on start up:

### ISSUE THREAD

**Issue by hornc** [Byzantium/Byzantium#134]
I have got distracted mucking about with Byzantium's Firefox browser and found the causes of these console errors:

using downloads/byzantium-0.2a-20120627-2142.iso   , NOT  running copy2ram

1) Firefox attempts and fails to load a Livemark Service xml file:

```
Error: Livemark Service: feed processor received an invalid channel for http://fxfeeds.mozilla.com/en-US/firefox/headlines.xml
Source File: resource:///components/nsLivemarkService.js
Line: 793
```

Apparently to do with the Firefox default live bookmark 'Latest Headlines'
Looks like this entry lives in the places.sqlite and maybe places.sqlite-wal -- I'm not sure how you would best remove this, but I imagine you'd want to to stop things 'phoning home' like this...

2) Could not read chrome manifest:

```
Could not read chrome manifest file '/usr/lib/firefox-9.0.1/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}/chrome.manifest'.
```

Looks like a bug with firefox Add ons:
https://bugzilla.mozilla.org/show_bug.cgi?id=586610

adding an empty chrome.manifest file stops the msg from showing FWIW..  not sure whether it is important though.

3) CSS font error:

```
Warning: Error in parsing value for 'font'.  Declaration dropped.
Source File: http://localhost:8080/css/text.css
Line: 15
```

And from the css file: 
    body {
      font: Arial Unicode MS, Lucida Sans Unicode, sans-serif;
    }

I replaced the offending line with:
       font-family: sans-serif;

and things looked nicer :)

**Comment by virtadpt** [comment]
It may not be possible to disable livemarks: https://bugzilla.mozilla.org/show_bug.cgi?id=436250

**Comment by virtadpt** [comment]
For what it's worth I just grepped every .js script in the default Byzantium Linux install, and none of them include the string 'fxfeeds', which is in the URI that Firefox's Livemarks service tries to load.  The resource script is nsLivemarkService.js, which I can't find.

The Mozilla documentation says that deleting all livemarks should disable the service.  places.sqlite is a SQLite database, so I'll go through it tomorrow and see if I can find it and drop the relevant lines.
