### ISSUE TITLE
Microblog not found

### ISSUE THREAD

**Issue by ElephantNinja** [Byzantium/Byzantium#135]
In Byzantium 0.2A-RC  byzantium-0.2a-RC-20120628-2327

Activated Microlog service on mesh host.

Connected client computer to mesh and listed 'Mesh Services'  - Microblog service listed. 

Clicking Microblog link opens error message page:

"NOT FOUND the requested url /microblog was not found on this server."

**Comment by haxwithaxe** [comment]
we are ditching status.net so we haven't (and won't) fixed this. Thanks for reporting it though.
