### ISSUE TITLE
System Status page does not show any network interface details when connected

### ISSUE THREAD

**Issue by hornc** [Byzantium/Byzantium#137]
This only affects one of my laptops -- Dell Lattitude D505
iso: byzantium-0.2a-RC-20120628-2327.iso   , copy2ram disabled

Network card: 01:03.0 Network controller: Intel Corporation PRO/Wireless 2200BG [Calexico2] Network Connection (rev 05)

I think this is caused by something else other than issue #132 (second part), because my second laptop shows status info even when it suffers from issue #132

I was hoping to investigate further, but have ran out of time. The main annoyance with this is that it is difficult to find the IP address of the system once the network is up and running.

**Comment by hornc** [comment]
I figured out the reason for this -- the status query from status.py expects the wireless interface to be called 'wlan'
  query = "SELECT client_interface FROM wireless WHERE client_interface LIKE 'wlan%';"

for some reason the wireless interface on that laptop is called eth1..

Output from network.sqlite wireless table: select \* from wireless;
no|eth1:1|yes|3|Byzantium|eth1

Replacing wlan%  with eth% in the two SQL queries in status.py and restarting control_panel.py gave me statuses as expected.
I don't know how common it is having a wireless interface called eth1 instead of wlan, or why it gets called that on my Dell, but that's the cause of this issue. Googling for 'wireless eth1' gives plenty of hits -- I couldn't find an explanation, but doesn't seem to be an actual technical problem (i.e wireless works fine), it just confuses people...

**Comment by virtadpt** [comment]
Good catch!

I don't know how common it is for wireless interfaces to be called /eth[0-9]*/i.  I know that Haxwithaxe has a few laptops like this, and I think that Sitwon has one or two like that, but I don't.  I'm going to update the SQL query in status.py and push it to the repo.  The next RC .iso will have that fix incorporated.

**Comment by virtadpt** [comment]
Fixed in commit 413d078a89b2af1a1713f4effc9a1070b4967b16.  Rebuilding the Byzantium module and then building an RC ISO.

**Comment by hornc** [comment]
Ooops, just tried one of the new isos, and its better, but there are two SQL queries, one for each table, that needed adjusting. The other one is on line 95

**Comment by virtadpt** [comment]
Fixed in commit 7c76ef0e3660aec8e94d442dce2edcbe24258907.
