### ISSUE TITLE
porteus/erlang doesn't build.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#14]
Trying to build the Erlang Porteus module fails with the following error:
- export 'http://www.erlang.org/download/otp_doc_man_R14B02.tar.gz"'
  ../../build.sh: line 8: export: `http://www.erlang.org/download/otp_doc_man_R14B02.tar.gz"': not a valid identifier
  make: **\* [../pkgs/erlang-otp-14B02-i486-1_SBo.tgz] Error 1

**Comment by virtadpt** [comment]
Isolated problem to Byzantium/porteus/erlang/src/erlang-otp/erlang-otp.info.  When running the file through the sed statement in Byzantium/porteus/build.sh, the variable in the  .info file produces an unusual result.

DOWNLOAD="http://www.erlang.org/download/otp_src_R14B02.tar.gz \
          http://www.erlang.org/download/otp_doc_man_R14B02.tar.gz"

results in:

DOWNLOAD
          http://www.erlang.org/download/otp_doc_man_R14B02.tar.gz"

**Comment by virtadpt** [comment]
I suspect that the trailing " character is part of the problem.  Running the commands in build.sh in sequence by hand seems to support this.  Perhaps this line should not be split across two lines?  It also kills my root shell used in this testing, and I crash back to a shell running as the unprivileged guest user.

Running the process implemented by the build.sh script by hand shows that the source code archives download as expected, extract as expected, and compile as expected.

Is the for loop in build.sh really necessary?

**Comment by haxwithaxe** [comment]
the specific problem in build.sh fixed please try again.

**Comment by virtadpt** [comment]
Updated repository on test virtual machine, got a clean build.  It worked.

Shall we close this ticket?

**Comment by haxwithaxe** [comment]
aye
