### ISSUE TITLE
add rfkill and related support for enabling/disabling wireless interfaces at the hardware level

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#140]
rfkill (the cli tool) is used to manage the rfkill /sys directories which control/display the otherwise be controlled by the pesky wifi on/off hardware switches.

**Comment by virtadpt** [comment]
This would be useful for detecting whether or not wireless interfaces have been soft-killed, and if so automagically turning them back on.  rfkill is also useful for probing the status of wireless interfaces.

**Comment by haxwithaxe** [comment]
already in porteus v1.2+
