### ISSUE TITLE
X server fails to boot on MacBook Pro + Nvidia 320M

### ISSUE THREAD

**Issue by yuvadm** [Byzantium/Byzantium#141]
When booting v0.2a on a MacBook Pro circa 2010, X server fails to load with a segfault (stack trace soon).

Graphics card details:

```
NVIDIA GeForce 320M:
  Chipset Model:    NVIDIA GeForce 320M
  Type: GPU
  Bus:  PCI
  VRAM (Total): 256 MB
  Vendor:   NVIDIA (0x10de)
  Device ID:    0x08a0
  Revision ID:  0x00a2
  ROM Revision: 3533
```

**Comment by virtadpt** [comment]
Found it in the Porteus Linux forums - the Noveau drivers don't work, we need to add the true-blue nVidia drivers.

Source: http://forum.porteus.org/viewtopic.php?f=81&t=597

**Comment by virtadpt** [comment]
Please try the latest RC of v0.3.2a?

**Comment by yuvadm** [comment]
@virtadpt sure, will test later today

**Comment by virtadpt** [comment]
Any luck?

**Comment by virtadpt** [comment]
No response in two months, closing out in preparation for v0.5b.
