### ISSUE TITLE
Mouse not working on Acer Aspire One under KDE.  Works under LXDE.

### ISSUE THREAD

**Issue by ITechGeek81** [Byzantium/Byzantium#143]
Mouse (touchpad) on Acer Aspire One not working under KDE.  The mouse works just fine under LXDE.
## Output from psinfo

script by jayflood
.

====== USER INFO =====
User is: guest
.
===== MACHINE INFO =====
Platform: i686
Kernel: 3.1.8-porteus
Processor: Intel(R) Atom(TM) CPU N270   @ 1.60GHz
Base Board Information
    Manufacturer: Acer
##     Product Name: Aspire one      

```
Serial Number: Base Board Serial Number
Asset Tag: Base Board Asset Tag
Features:
    Board is a hosting board
```
## 

```
Location In Chassis: Base Board Chassis Location
Chassis Handle: 0x0003
Type: Motherboard
```

MemTotal:        1023268 kB
MemFree:           91404 kB
Bootparam: root=/dev/ram0 rootfstype=ext4 rw initrd=/boot/initrd.xz vga=F00 lxde autoexec=xconf;telinit~4 copy2ram BOOT_IMAGE=/boot/vmlinuz 
.
===== LIVE DEBUG INFO =====
# Recognized devices:

/dev/sdb1: UUID="72d2ab06-b430-4cd7-bdaf-b88dddde9bb5" TYPE="ext2" 
# Porteus boot device:

sdb1
# Porteus data found in:

/memory/copy2ram
# Changes are stored in:

none
# Non standard /rootcopy dir:

none
# Loaded modules:

base/000-kernel.xzm
base/001-core.xzm
base/002-xorg.xzm
base/003-lxde.xzm
base/004-kde.xzm
base/005-kdeapps.xzm
base/006-koffice.xzm
base/007-devel.xzm
base/008-firefox.xzm
modules/000-byzantium.xzm
.
===== SOUND INFO =====
Sound card:  0 [Intel          ]: HDA-Intel - HDA Intel
                      HDA Intel at 0x56340000 irq 44
Sound driver: Advanced Linux Sound Architecture Driver Version 1.0.24.
.
===== PARTITION INFO =====
Mounted: 
/dev/sdb1      ext2   29G  893M   27G   4% /media/usbhd-sdb1
.
===== OPTICAl DRIVE =====

.
===== USB INFO =====
Removables: MKNUFDVP32GB
Removable status: sd0:0:0:0:[sda]Protect
sd6:0:0:0:[sdb]Protect
.
lsusb: Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 002: ID 13fe:5000 Kingston Technology Company Inc. 
Bus 001 Device 003: ID 064e:d101 Suyin Corp. Acer CrystalEye Webcam
.
===== SCREEN INFO =====
Screen 0: minimum 320 x 200, current 1024 x 600, maximum 4096 x 4096
.
===== ACTIVATED MODULES =====
000-byzantium.xzm
000-kernel.xzm
001-core.xzm
002-xorg.xzm
003-lxde.xzm
004-kde.xzm
005-kdeapps.xzm
006-koffice.xzm
007-devel.xzm
008-firefox.xzm
.
===== NETWORK INFO =====
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:565 (565.0 b)  TX bytes:565 (565.0 b)
.
search example.net
.
===== PCI INFO =====
<code>
lspci: 00:00.0 Host bridge [0600]: Intel Corporation Mobile 945GME Express Memory Controller Hub [8086:27ac](rev 03)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: agpgart-intel
    Kernel modules: intel-agp
00:02.0 VGA compatible controller [0300]: Intel Corporation Mobile 945GME Express Integrated Graphics Controller [8086:27ae](rev 03)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: i915
    Kernel modules: intelfb, i915
00:02.1 Display controller [0380]: Intel Corporation Mobile 945GM/GMS/GME, 943/940GML Express Integrated Graphics Controller [8086:27a6](rev 03)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
00:1b.0 Audio device [0403]: Intel Corporation N10/ICH 7 Family High Definition Audio Controller [8086:27d8](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: snd_hda_intel
    Kernel modules: snd-hda-intel
00:1c.0 PCI bridge [0604]: Intel Corporation N10/ICH 7 Family PCI Express Port 1 [8086:27d0](rev 02)
    Kernel driver in use: pcieport
    Kernel modules: shpchp
00:1c.1 PCI bridge [0604]: Intel Corporation N10/ICH 7 Family PCI Express Port 2 [8086:27d2](rev 02)
    Kernel driver in use: pcieport
    Kernel modules: shpchp
00:1c.2 PCI bridge [0604]: Intel Corporation N10/ICH 7 Family PCI Express Port 3 [8086:27d4](rev 02)
    Kernel driver in use: pcieport
    Kernel modules: shpchp
00:1d.0 USB controller [0c03]: Intel Corporation N10/ICH 7 Family USB UHCI Controller #1 [8086:27c8](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: uhci_hcd
00:1d.1 USB controller [0c03]: Intel Corporation N10/ICH 7 Family USB UHCI Controller #2 [8086:27c9](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: uhci_hcd
00:1d.2 USB controller [0c03]: Intel Corporation N10/ICH 7 Family USB UHCI Controller #3 [8086:27ca](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: uhci_hcd
00:1d.3 USB controller [0c03]: Intel Corporation N10/ICH 7 Family USB UHCI Controller #4 [8086:27cb](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: uhci_hcd
00:1d.7 USB controller [0c03]: Intel Corporation N10/ICH 7 Family USB2 EHCI Controller [8086:27cc](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: ehci_hcd
00:1e.0 PCI bridge [0604]: Intel Corporation 82801 Mobile PCI Bridge [8086:2448](rev e2)
00:1f.0 ISA bridge [0601]: Intel Corporation 82801GBM (ICH7-M) LPC Interface Bridge [8086:27b9](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel modules: leds-ss4200, intel-rng
00:1f.1 IDE interface [0101]: Intel Corporation 82801G (ICH7 Family) IDE Controller [8086:27df](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: ata_piix
00:1f.2 SATA controller [0106]: Intel Corporation 82801GBM/GHM (ICH7-M Family) SATA Controller [AHCI mode] [8086:27c5](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: ahci
00:1f.3 SMBus [0c05]: Intel Corporation N10/ICH 7 Family SMBus Controller [8086:27da](rev 02)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: i801_smbus
    Kernel modules: i2c-i801
01:00.0 Ethernet controller [0200]: Atheros Communications Inc. AR242x / AR542x Wireless Network Adapter (PCI-Express) [168c:001c](rev 01)
    Subsystem: Foxconn International, Inc. Device [105b:e008]
    Kernel driver in use: ath5k
    Kernel modules: ath5k
03:00.0 Ethernet controller [0200]: Atheros Communications Inc. AR8121/AR8113/AR8114 Gigabit or Fast Ethernet [1969:1026](rev b0)
    Subsystem: Acer Incorporated [ALI] Device [1025:019c]
    Kernel driver in use: ATL1E
    Kernel modules: atl1e</code>
.
.
===== LOGS INFO =====
dmesg | tail 
.
[   23.971490] Registered led device: ath5k-phy0::tx
[   23.971526] ath5k phy0: Atheros AR2425 chip found (MAC: 0xe2, PHY: 0x70)
[   24.276311] Synaptics Touchpad, model: 1, fw: 7.2, id: 0x1c0b1, caps: 0xd04773/0xa40000/0xa0000
[   24.291426] Console: switching to colour frame buffer device 128x37
[   24.298895] fb0: inteldrmfb frame buffer device
[   24.298900] drm: registered panic notifier
[   24.298974] [drm] Initialized i915 1.6.0 20080730 for 0000:00:02.0 on minor 0
[   24.384623] input: SynPS/2 Synaptics TouchPad as /devices/platform/i8042/serio1/input/input9
[   24.426653] mousedev: PS/2 mouse device common for all mice
[   53.120634] NET: Registered protocol family 10
.
.
cat /var/log/messages | tail
.
Jul 15 17:50:06 (none) avahi-daemon[2536]: Loading service file /services/ssh.service.
Jul 15 17:50:06 (none) avahi-daemon[2536]: Loading service file /services/udisks.service.
Jul 15 17:50:06 (none) avahi-daemon[2536]: Network interface enumeration completed.
Jul 15 17:50:06 (none) avahi-daemon[2536]: Server startup complete. Host name is byzantium.local. Local service cookie is 3859381583.
Jul 15 17:50:06 (none) avahi-daemon[2536]: Service "byzantium" (/services/udisks.service) successfully established.
Jul 15 17:50:06 (none) avahi-daemon[2536]: Service "byzantium" (/services/ssh.service) successfully established.
Jul 15 17:50:06 (none) avahi-daemon[2536]: Service "byzantium" (/services/sftp-ssh.service) successfully established.
Jul 15 17:50:06 (none) avahi-dnsconfd[2543]: Successfully connected to Avahi daemon.
Jul 15 17:50:12 (none) acpid: client connected from 2771[0:0]
Jul 15 17:50:12 (none) acpid: 1 client rule loaded
..

**Comment by virtadpt** [comment]
I noticed the same thing on my EeePC 900.  Hardware layout to come.

I also noticed that this started after the reskinning of KDE Trinity.  There may be a connection, there may not be, but we should investigate it.

**Comment by virtadpt** [comment]
Please try the latest RC of v0.3.2a to test this fix?

**Comment by virtadpt** [comment]
Is this still a problem?

**Comment by ITechGeek81** [comment]
I haven't tried this on mine yet, but I just tried it on someone's D250 (I think one model newer than mine) and it worked good.  I'm trying to try and test it on mine later (or tomorrow).

**Comment by ITechGeek81** [comment]
Mouse is working on Acer Aspire One D150 and D250 models.
