### ISSUE TITLE
Mesh Gateway to Internet on eth0 does not function properly

### ISSUE THREAD

**Issue by ghost** [Byzantium/Byzantium#144]
I've included ifconfig output. route -v hangs - let me know what other info is useful going forward.

---

eth0      Link encap:Ethernet  HWaddr 00:15:58:32:21:B5  
          inet addr:10.2.8.26  Bcast:10.2.8.255  Mask:255.255.255.0
          inet6 addr: fe80::215:58ff:fe32:21b5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:647 errors:0 dropped:387 overruns:0 frame:0
          TX packets:89 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:64061 (62.5 Kb)  TX bytes:21616 (21.1 Kb)
          Interrupt:16 Memory:ee000000-ee020000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:892 errors:0 dropped:0 overruns:0 frame:0
          TX packets:892 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:172406 (168.3 Kb)  TX bytes:172406 (168.3 Kb)

wlan0     Link encap:Ethernet  HWaddr 00:18:DE:AF:B5:0D  
          inet addr:192.168.199.183  Bcast:192.168.255.255  Mask:255.255.0.0
          inet6 addr: fe80::218:deff:feaf:b50d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:306 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1302 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:32467 (31.7 Kb)  TX bytes:121404 (118.5 Kb)

wlan0:1   Link encap:Ethernet  HWaddr 00:18:DE:AF:B5:0D  
          inet addr:10.183.127.1  Bcast:10.255.255.255  Mask:255.0.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

---

I configured wlan0 to be the mesh interface, and eth0 (DHCP-issued IP) to be the gateway.

eth0 ends up properly configured and has an IP Address. I cannot nslookup/ping anything from the Byzantium system (T60).

I can successfully connect to the mesh from another client, but it can only reach byzantium-hosted resources, not external hosts. DNS Lookups fail as well from client and server.

**Comment by Sitwon** [comment]
Could you try sharing the output of 'route -n' and 'cat /etc/resolv.conf'?

Thanks,
Ben the Pyrate

On Mon, Jul 16, 2012 at 1:38 PM, DrainTheLibrary <
reply@reply.github.com

**Comment by ghost** [comment]
## Client IFConfig (OS X 10.6.8)

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
    options=3<RXCSUM,TXCSUM>
    inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
    inet 127.0.0.1 netmask 0xff000000 
    inet6 ::1 prefixlen 128 
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    options=2b<RXCSUM,TXCSUM,VLAN_HWTAGGING,TSO4>
    ether c4:2c:03:12:8b:f5 
    media: autoselect (none)
    status: inactive
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether d8:30:62:4f:77:e2 
    inet6 fe80::da30:62ff:fe4f:77e2%en1 prefixlen 64 scopeid 0x5 
    inet 10.187.196.64 netmask 0xff000000 broadcast 10.255.255.255
    media: autoselect
    status: active
fw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 4078
    lladdr e8:06:88:ff:fe:e5:80:0e 
    media: autoselect <full-duplex>
    status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
    ether 0a:30:62:4f:77:e2 
    media: autoselect
    status: active

## Server IFConfig (Byzantium 0.2a)

eth0      Link encap:Ethernet  HWaddr 00:15:58:32:21:B5  
          inet addr:10.2.8.26  Bcast:10.2.8.255  Mask:255.255.255.0
          inet6 addr: fe80::215:58ff:fe32:21b5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:240 errors:0 dropped:143 overruns:0 frame:0
          TX packets:70 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:23293 (22.7 Kb)  TX bytes:20541 (20.0 Kb)
          Interrupt:16 Memory:ee000000-ee020000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:320 errors:0 dropped:0 overruns:0 frame:0
          TX packets:320 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:77302 (75.4 Kb)  TX bytes:77302 (75.4 Kb)

wlan0     Link encap:Ethernet  HWaddr 00:18:DE:AF:B5:0D  
          inet addr:192.168.79.200  Bcast:192.168.255.255  Mask:255.255.0.0
          inet6 addr: fe80::218:deff:feaf:b50d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:229 errors:0 dropped:0 overruns:0 frame:0
          TX packets:321 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:28396 (27.7 Kb)  TX bytes:54623 (53.3 Kb)

wlan0:1   Link encap:Ethernet  HWaddr 00:18:DE:AF:B5:0D  
          inet addr:10.187.196.1  Bcast:10.255.255.255  Mask:255.0.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

## Client resolv.conf

#

# Mac OS X Notice

#

# This file is not used by the host name and address resolution

# or the DNS query routing mechanisms used by most processes on

# this Mac OS X system.

#

# This file is automatically generated.

#
domain byzantium.mesh
nameserver 10.187.196.1

## Server resolv.conf (Note: These IPs look familiar to me, and I believe to be the correct DHCP issued DNS servers from the network I am on)

# Generated by dhcpcd from eth0

# /etc/resolv.conf.head can replace this line

nameserver 10.1.20.97
nameserver 10.1.20.98
nameserver 10.11.20.26

# /etc/resolv.conf.tail can replace this line

## client route to google.com

   route to: 10.187.196.1
destination: 10.187.196.1
  interface: en1
      flags: <UP,HOST,DONE,LLINFO,WASCLONED,IFSCOPE,IFREF>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500      1193 

## server route -n

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.2.8.1        0.0.0.0         UG    202    0        0 eth0
10.0.0.0        0.0.0.0         255.0.0.0       U     0      0        0 wlan0
10.2.8.0        0.0.0.0         255.255.255.0   U     202    0        0 eth0
127.0.0.0       0.0.0.0         255.0.0.0       U     0      0        0 lo
192.168.0.0     0.0.0.0         255.255.0.0     U     0      0        0 wlan0

At this point I think the issue is DNS Related (also, can we get nslookup added to byzantium? seems to be missing unless i'm supposed to be using something else I don't know about...)

**Comment by virtadpt** [comment]
The output of ifconfig looks about right to me.  So do the routes and the contents of /etc/resolv.conf.

Could you run the command `captive-portal.sh list` and paste the output?  It sounds like NAT isn't working as expected.

**Comment by virtadpt** [comment]
Have you been able to reproduce this problem recently?

**Comment by haxwithaxe** [comment]
we need to add nslookup and dig to the system either way. if they are in 1.2 we'll call that part done.

**Comment by ghost** [comment]
No longer own the original hardware in question here (not sure if issue was HW specific)

**Comment by virtadpt** [comment]
Closing - ENOBOX
