### ISSUE TITLE
Control Panel Page titles/header titles/Controls titles are all mismatched

### ISSUE THREAD

**Issue by ghost** [Byzantium/Byzantium#145]
There's some severe usability issues as a result of inconsistent naming terminology in the Control Panel.

Example:

Click "Configure Mesh Network" from the control panel
The page title in the browser is "Byzantium Node Mesh Configuration"
The page header is called "Configure Mesh Interfaces"

Very disorienting with all the conflicting naming, would be difficult to give directions to someone/write documentation on

**Comment by virtadpt** [comment]
Good call.  We need to run the HTML templates past someone who knows UI (Celeste?) and can suggest a better convention.

**Comment by virtadpt** [comment]
Irrelevant.  We removed the control panel in v0.3a.  As for the release after that, LuCI does this for us.
