### ISSUE TITLE
Add form field validation on Configure Network Interfaces wlan0 fields

### ISSUE THREAD

**Issue by ghost** [Byzantium/Byzantium#146]
"Enter the wireless channel and ESSID the network interface will use" entry boxes allow for invalid entries, and also doesn't allow 802.11n channel value entries.

Suggest changing the Channel textbox to a Dropdown based on detected hardware capabilities (if possible) 

Valid form values should be:

Channels:

http://en.wikipedia.org/wiki/List_of_WLAN_channels

ESSID:

I believe this is 32 characters maximum (but can't find official spec)

**Comment by virtadpt** [comment]
Yep, needs sanity checking.  I'm considering taking out that text entry bit entirely to streamline the configuration process.  It also needs to be 802.11n compliant, good catch.

**Comment by virtadpt** [comment]
Irrelevant.  The control panel is irrelevant so this no longer applies.
