### ISSUE TITLE
Compilation of mupdf failed.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#15]
cmake is not installed by default.  Details to follow.

**Comment by haxwithaxe** [comment]
details?

**Comment by virtadpt** [comment]
[output of decompression of tarball omitted...]
patching file jp3d/libjp3dvm/CMakeLists.txt
patching file libopenjpeg/CMakeLists.txt
openjpeg.SlackBuild: line 76: cmake: command not found
make[1]: **\* [../pkgs/openjpeg-1.4-i486-2_SBo.tgz] Error 127
make[1]: Leaving directory `/home/guest/Byzantium/porteus/mupdf/src'
make: **\* [pkgs/openjpeg-1.4-i486-2_SBo.tgz] Error 2

**Comment by virtadpt** [comment]
Looks like there needs to be a package for cmake to make this happen.  At least we won't have to include cmake in the full distro, it's just a compilation tool.

**Comment by virtadpt** [comment]
Converted cmake Slackware package into a Porteus module.  Converted libarchive as a dependency.

**Comment by virtadpt** [comment]
make[2]: Entering directory `/tmp/SBo/mupdf-0.8.165'
mkdir -p build/release
cc -O2 -march=i486 -mtune=i686 -Ifitz -Ipdf -Ixps -Iscripts -Wall -pipe -O2 -DNDEBUG -fomit-frame-pointer`pkg-config --cflags freetype2`-o build/release/filt_jpxd.o -c fitz/filt_jpxd.c
fitz/filt_jpxd.c:4:22: fatal error: openjpeg.h: No such file or directory
compilation terminated.
make[2]: *** [build/release/filt_jpxd.o] Error 1
make[2]: Leaving directory`/tmp/SBo/mupdf-0.8.165'
make[1]: **\* [../pkgs/mupdf-0.8.165-i486-1_SBo.tgz] Error 2
make[1]: Leaving directory `/home/guest/Byzantium/porteus/mupdf/src'
make: **\* [pkgs/mupdf-0.8.165-i486-1_SBo.tgz] Error 2

muPDF Makefiles don't know where to find the temp directory that openjpeg is installed to.

**Comment by virtadpt** [comment]
Deleted from source tree because Porteus already includes kPDF.
