### ISSUE TITLE
Make control panel stateless.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#151]
During testing, it's been shown that making the control panel stateful (by snapshotting the system state in SQLite databases) is not a good idea, because the status of the system can change without the databases being updated.  This can lead to misleading user output and seemingly illogical system activity ("What do you mean, the wireless card isn't in Ad-Hoc mode?")

Code that references the SQLite databases needs to be weeded out and replaced with calls to helper methods that use system.Popen() or parse files in _/proc_ and _/sys_ to get configuration and status information directly from the kernel and not from a possibly out of date database.

To make it easier to manage, this should be done one module at a time.  This should also be done after all of the outstanding pull requests are reviewed and merged.

**Comment by haxwithaxe** [comment]
this will be part of the Model section of the MVC rework.

**Comment by virtadpt** [comment]
In v0.3a we got rid of the control panel, so this is irrelevant.

In v0.4a we're migrating to LuCI, so this will be accomplished.
