### ISSUE TITLE
Consider pseudorandomly picking ESSIDs for wireless interfaces.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#154]
Clients' wi-fi cell membership is based upon BSSID (http://www.javvin.com/wireless/BSSID.html) and not ESSID (network name).  So, as long as mesh nodes are configured with the same BSSID and channel/frequency, it shouldn't matter what the ESSID is.  So, it should be possible to add some code to the control panel to either pseudo-randomly generate or pick ESSIDs from a list to make each node's wireless configuration look more or less the same.  "Linksys" and "Free Public Wifi" came up in discussion at HOPE Number Nine.

Sitwon noticed this, I think we should experiment with it to see whether or not (and how well) it works in practice.

**Comment by haxwithaxe** [comment]
maybe a site survey to pick a name that will blend in?
"[a-zA-Z]{5}[0-9]" in verizon territory or linksys, hp-setup, or "Free Public WiFi" in urban environments.

edit:fucking markdown :/

**Comment by virtadpt** [comment]
`iwlist $interface scanning | grep 'ESSID'`

**Comment by SpartacusAU** [comment]
Why not scan for ESSID's and copy one and add " B" to the end of what ever is there. Very subtle. "Free Public WiFi B" looks legit, and as good as a nod to those who know what it represents.

**Comment by virtadpt** [comment]
This is a mailing list discussion and not a ticket.
