### ISSUE TITLE
Make it possible for someone running a node to add arbitrary services to the control panel.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#157]
Obviously, this will work best on nodes that have persistent storage.

Due to the fact that we're phasing out the SQLite back-end databases, the exact implementation will be up in the air.  But I'll try.

Okay.  Let's assume that the node's admin has set up a network application on zir node that does stuff.  It must have an initscript that starts and stops the service.  We can supply a template BSD-style initscript that does most of what we need but ultimately it's the user's responsibility to do it right.  They'll have to put the script in `/etc/rc.d`, too.

The user clicks on an "Add an app" link in the control panel.  The app asks for the name of the app ("Rote") and the name of the initscript ("rc.rote") - because it has to be in a specific place we can assume the `/etc/rc.d` bit (though we can also detect this string during entry sanitization).  The control panel then sets mode 0755 on the new initscript and starts it (`/etc/rc.d/rc.rote start`).

By requiring a certain layout of the script, we know that there has to be a PID file in `/var/run` written by whatever it is the user wants to set up.  This means that we can then pick the name of the process out of its process directory in `/proc/[0-9]?*`, run `netstat -pan`, and figure out what network port that process has opened.

With the name of the app, the protocol (TCP or UDP), and port the control panel can then write a simple Avahi service descriptor in `/etc/avahi/services` called "<name>.service" that describes the user's service.  Then avahi-daemon is bounced and the presence of the service is announced on the mesh, where it's picked up by every node's service directory.

**Comment by haxwithaxe** [comment]
we might be able to make the control and view pluggable so that a "thirdparty" service can be added without altering the control panel code. we also can read a config file instead of assuming the bits will be in certian places.

**Comment by virtadpt** [comment]
This may be possible with LuCI.  We won't know until v0.4a or therabouts.
