### ISSUE TITLE
Cold RAM defence?

### ISSUE THREAD

**Issue by SpartacusAU** [Byzantium/Byzantium#158]
On the subject of security, since Byzantium depends on the volatility of RAM for part of security, is there protection for 'Cold RAM' attacks?

 I recall FreeBSD has protection based on changes in RAM temperature.

I'm wondering if this is already incorporated in Byzantium, and if not would it be worth considering?

**Comment by virtadpt** [comment]
There isn't yet, but it could be added.  TAILS already does this, and we can crib their technique and implement it on our own.

I didn't know that FreeBSD had anti-coldboot protection built in; working with FreeBSD 8 and 9 lately I haven't seen anything about it in the Handbook or the kernel source code.  Do you have references for this?

**Comment by SpartacusAU** [comment]
The only reference to it was a video article I saw on BoingBoing in  late 2007 early 2008. Can't find it in their archives.... yet. I'll keep looking though.

From memory they showed a box shot of FreeBSD4.0, it had a cartoon picture of a viking longboat with vikings on it.

Sorry I can't offer more so far, I was half expecting to hear "yeah we got that covered already".

Some internet searches found interesting pages.

A BIOS level defence:
http://www.derkeiler.com/Newsgroups/sci.crypt/2008-09/msg00071.html

A recent general discussion of the topic:
https://freedom-to-tinker.com/blog/felten/new-research-result-cold-boot-attacks-disk-encryption/

Hardware solutions?
laptop computer; glue the RAM access panel shut with epoxy. How often to people open this panel anyway?
Defense method to slow down attacker and allow entropy in RAM to erase bits.

Desktop computer; as many screws as possible holding the case closed, using a different security bit for each screw.
Defense method to slow down attacker and allow entropy in RAM to erase bits.

I recommend some kind of defense to cold RAM be coded in if possible.

**Comment by SpartacusAU** [comment]
The article is here but the the video is gone.

http://boingboing.net/2008/05/page/29

**Comment by SpartacusAU** [comment]
found it finally

http://www.youtube.com/watch?v=C_VsNYwGM_k

The *nix mentioned was OpenBSD4.3,  sorry, my mistake it's something I saw once 4+ years ago.

**Comment by virtadpt** [comment]
Rather than suggesting hardware modifications to potential first-responders, let's see how other people have done it and figure out where to go from there.

**Comment by SpartacusAU** [comment]
+1
This might be helpful.
Some DDR 3 RAM modules have temperature sensors built in, so monitoring them maybe what can be used to trigger the defense procedure.
Other motherboard sensors could be used to see if the RAM is cooling disproportionately to the rest of the hardware.
compare   dT (RAM)/dt    vs  dT(Board)/dt   vs   dT(CPU)/dt  vs    dT( ??)/dt   vs constant value?

For a smaller device there is usually a temperature sensor which could be used as a proxy for the RAM temperature as its hard to only heat/ freeze only part of such a small device.
dT(board)/dt   vs previous norms of temperature change gradient.
 ie boot /shut down, hot indoors to cold outside.
there may be an absolute figure we could apply per device form factor or model.

May require logging temperature for the node to find sharp increases and decreases in temp from normal use.

It's worth nothing that when cold RAM attack was first publicized (2008) DDR3 ram was new and still uncommon. Previous DDR2 chips did not have the built in temperature sensor. The addition of this temperature sensor was co incidental rather than as a response to the attack.

**Comment by Sitwon** [comment]
Based on my understanding of the cold RAM attack, I don't believe it is possible that we could defend against this with software. Even if we could, I think this is outside the scope of our project.
