### ISSUE TITLE
Color palate - colorblindness issue.

### ISSUE THREAD

**Issue by SpartacusAU** [Byzantium/Byzantium#159]
I notice when setting up interfaces for the node that the colors used were red and green.
Just like traffic lights, green is go/on, red is no go/ off   makes perfect sense, if you can tell the difference between red and green.

Approximately 10% of the male population is red-green colorblind.

I was wondering if you would consider changing this color convention to another color pair to represent on/ off.

I would suggest blue/ yellow, green/yellow or green/blue.

Alternatively or additionally you might consider different color saturation to further distinguish the difference between the two colors.

For the more critical parts of the UI color coding you may wish to add a user customizable interface where they can choose which color pair suit them best for at least the critical parts of the UI,  such as setting up mesh and NIC interfaces.

If you follow this route you will end up with some variables that say colorPositive and colorNegative and of course something else that sets them, similar to the 'no more magic numbers' issue.

10% of male users could prove to be a segment we don't want to leave behind.

This isn't a critical issue now, but I think it's something to look into prior to final build.

**Comment by haxwithaxe** [comment]
+1 on this
we might want to not use colors per se on the buttons. i think at the very least we should have the state explicitly written out next to the buttons and grey-out things that are not options. having colorblindness adaptive profiles might be something we stick in 1.0 but it's a primary stylistic issue so i'll give this to seeele and she can work her css magic on it if she has time.

**Comment by virtadpt** [comment]
Why don't we change it to something more universal?

"Configured" "Not configured" "Active"

This also brings in the need for translations (where is that i18n ticket when I need it?!)

**Comment by virtadpt** [comment]
Ticket #13.

**Comment by haxwithaxe** [comment]
i think enabled vs disabled is good enough for now at least and we might just want to use highlighted and not highlighted instead of colorizing both states.

**Comment by haxwithaxe** [comment]
i like that idea a lot since it allows a more visceral identification of meaning to the point that illiterate people can understand it. even if it is just that one bit. it is also a preexisting global standard for traffic signals and signage.

**Comment by SpartacusAU** [comment]
Expanding that idea a little further:
Difficult to describe with words.
My idea for the network interfaces GUI.

http://randomtopicanalysis.wordpress.com/2012/08/01/byzantuim-interface-concept/

You can click on the image for a slightly better resolution image.

PS is there a way to post images here?

**Comment by virtadpt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 08/01/2012 09:33 AM, SpartacusAU wrote:

> Expanding that idea a little further: Difficult to describe with
> words. My idea for the network interfaces GUI. 
> http://randomtopicanalysis.wordpress.com/2012/08/01/byzantuim-interface-concept/

Nice!

> You can click on the image for a slightly better resolution image.
> PS is there a way to post images here?

I don't think there is...

How much coding would be required to implement the "drag icon into
this column" functionality you speak of?  This is out of my
non-existent web design expertise.

Seeing as how we're eventually aiming for "already configured, click
to reconfigure" functionality in the control panel, it may not be
worth implementing this.  It would, however, be worth exploring as a
way of informing the user about the current configuration of the node.

---

The Doctor [412/724/301/703] [ZS]
Developer, Project Byzantium: http://project-byzantium.org/

PGP: 0x807B17C1 / 7960 1CDC 85C9 0B63 8D9F  DD89 3BD8 FF2B 807B 17C1
WWW: https://drwho.virtadpt.net/

Activate interlock! Dynotherms connected! Infracells up! Megathrusters
are go!

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.19 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iEYEARECAAYFAlAZZxgACgkQO9j/K4B7F8HJ8QCgvvdiaCFqShu9rP1b4qJIMl1X
m24AmQHqjpF36HUnjubpZt70Et0u7msm
=dUOM
-----END PGP SIGNATURE-----

**Comment by SpartacusAU** [comment]
Already configured is a very desirable initial state.

Click and drag to column is just an idea,
It could also be click on the NIC button which then 'drills down' to give further info about the NIC, and a series of options of how the NIC can be reconfigured. 
The options in this NIC 'drill down' page could be visual reference to the GUI described or something else.

Quote:
How much coding would be required to implement the "drag icon into this column" functionality you speak of?
Reply:
I'm pretty sure it would fit between a pair of curly brackets {  place awesome code here! }

My coding experience; you don't seem to have much use for the languages I can vaguely code in  I.e Excel VBA, Java and BF. The languages you are using, I have heard of...so I'd probably just get in the way. But I do understand the basic concepts of coding. I do understand security quite well, which became and issue with a previous 'sponsor' in a trillion dollar incident. 
Please forgive my heresy.

I have a lot of experience working in large corporates on data orientated projects so I'm somewhat versed in explaining/simplifying and displaying information to the blind/colorblind/clueless. I think the concept interface passes those tests.

It would be waste to have a really intuitive interface and not have it interactive.

Hopefully an oddball like me may give some occasional good ideas and  prevent 'groupthink'.

Just ignore all the stupid things I say, but be sure in yourself _why_ they are stupid things.
I just really wanted to contribute to the the awesomeness this project will produce.

**Comment by haxwithaxe** [comment]
"I'm somewhat versed in explaining/simplifying and displaying information to the blind/colorblind/clueless"
dude ... you can explain things to the clueless ... nothing more is needed :P
also i like the interface idea. it would be easy enough for me to implement the drag and drop in javascript and that's saying quite a bit :P

**Comment by SpartacusAU** [comment]
There are 2 more pictures of proposed interface.

I'm suggesting that once an NIC is selected it is highlighted and other allowed possible sates are displayed (grey rectangles in the picture) so the user knows what states are allowable with the NIC. Increase the 'obviousness factor'.

Also adds some kind of visual representation to the internal rules of what can and should be done, which I don't fully understand yet.

There is of course scope for error messages when a disallowed configuration change is attempted.

http://randomtopicanalysis.wordpress.com/2012/08/01/byzantuim-interface-concept/

There is a question there too:
Can a wired interface be added to a mesh?

Yes I’m assuming there is another Byzantium node at the other end of the  Ethernet cable.

Would it matter if the other end of the Ethernet cable was attached to another OS?

Can't wait to D/L v0.3a  :)

**Comment by virtadpt** [comment]
There should be international guidelines for this sort of thing in industry. Manufacturers adhere to them for international sale. Maybe OSHA or the IEEE. Let's see what they recommend.
