### ISSUE TITLE
Compilation of apr Porteus module failed.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#16]
It failed in the same way that the Erlang package did.  The for.. loop in build.sh blows up the build, but if I go through the steps in that script one by one and just source the apr.info file, the compile proceeds normally.  The compile also dies because doxygen isn't installed, but that's a separate issue.

**Comment by haxwithaxe** [comment]
for loop fixed. unless doxygen issue isn't addressed elsewhere or fixed, then this ticket should be closed.

**Comment by virtadpt** [comment]
Did a `git pull` to update my local repository.  No dice.  Full output:

root@byzantium:/home/guest/Byzantium/porteus/apr# make
mkdir -p build
make -C src ../pkgs/apr-1.4.2-i486-2.tgz
make[1]: Entering directory `/home/guest/Byzantium/porteus/apr/src'
sh ../../build.sh apr
- set -e
- cd apr
- source ./apr.info
  ++ PRGNAM=apr
  ++ VERSION=1.4.2
  ++ HOMEPAGE=https://apr.apache.org/
  ++ DOWNLOAD=https://archive.apache.org/dist/apr/apr-1.4.2.tar.bz2
  ++ MD5SUM=4b00e8f70c067893d075577962656b35
  ++ DOWNLOAD_x86_64=
  ++ MD5SUM_x86_64=
  ++ MAINTAINER=
  ++ EMAIL=
  ++ APPROVED=
  ++ sed '$!N;s/[\n\r]+/ /'
  ++ cut -d = -f 1
  ++ cat ./apr.info
- for i in '`cat ./$1.info | sed '\''$!N;s/\\[\n\r]\+/ /'\'' | cut -d = -f 1`'
- export PRGNAM
- for i in '`cat ./$1.info | sed '\''$!N;s/\\[\n\r]\+/ /'\'' | cut -d = -f 1`'
- export VERSION
- for i in '`cat ./$1.info | sed '\''$!N;s/\\[\n\r]\+/ /'\'' | cut -d = -f 1`'
- export HOMEPAGE
- for i in '`cat ./$1.info | sed '\''$!N;s/\\[\n\r]\+/ /'\'' | cut -d = -f 1`'
- export '#'
  ../../build.sh: line 8: export: `#': not a valid identifier
  make[1]: *** [../pkgs/apr-1.4.2-i486-2.tgz] Error 1
  make[1]: Leaving directory`/home/guest/Byzantium/porteus/apr/src'
  make: **\* [pkgs/apr-1.4.2-i486-2.tgz] Error 2
  root@byzantium:/home/guest/Byzantium/porteus/apr#

**Comment by virtadpt** [comment]
Edited apr.info, took out command (the source of the /^#/, re-ran build.

Build errored out because doxygen isn't installed.  Checked new apr.info file into repository.

**Comment by virtadpt** [comment]
There doesn't seem to be a way to disable the use of doxygen in the configure script.

**Comment by virtadpt** [comment]
Converted Slackware doxygen package.  Retried compilation.  Success.
