### ISSUE TITLE
byzantium-v0.2a wont boot

### ISSUE THREAD

**Issue by vladoboss** [Byzantium/Byzantium#161]
I can't boot this version, on boot it says No operating system found. I burned the iso on usb stick as usual with dd
dd if=byzantium-v0.2a.iso of=/dev/sdb
I checked the gpg and it is valid:
gpg --verify byzantium-v0.2a.iso.asc
gpg: Signature made нед, 08 јул 2012 22:22:35 CEST using DSA key ID D6975C17
gpg: Good signature from "Project Byzantium (Byzantium Development Team) byzantium@hacdc.org"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 93F3 8B13 B52C D8F0 FA8D  03B3 37AA 847C D697 5C17

What could be the problem?

**Comment by vladoboss** [comment]
OK ignore it, I saw installation instructions :-)

**Comment by haxwithaxe** [comment]
thanks for reporting and solving your issue :P
