### ISSUE TITLE
Wicd Network Manager - error on start - command needs to access your computer's network cards

### ISSUE THREAD

**Issue by Ansssss** [Byzantium/Byzantium#163]
Run wicd-gtk from the console or launch it from the Internet>Wicd Network Manager icon. In both situations a popup appears with this message (complete with apostrophes):

Command 'needs 'to' 'access' 'your' 'computer'\''s' 'network' 'cards.' '/usr/sbin/wicd'' not found.

**Comment by virtadpt** [comment]
wicd is disabled because it conflicts with the control panel.  Start Firefox, it'll take you to the control panel.

**Comment by haxwithaxe** [comment]
i'm gonna call this one closed but i'm opening an issue to add generic network management to the control panel (if there isn't already one).

**Comment by virtadpt** [comment]
That means not excising the network configuration code I wrote, but refining it so it sucks less and moving it into a separate module (and thus sub-function of the control panel).

**Comment by haxwithaxe** [comment]
i've already started on an iproute2 api :P
