### ISSUE TITLE
captive_portal.py failed.  Returned code .

### ISSUE THREAD

**Issue by starbits** [Byzantium/Byzantium#164]
Using an HP Compaq 6910p laptop, when I configure network interfaces using the default settings, I get the above error (with no returned code).  Other devices, like my iPad, can see the mesh, but opening a browser window does nothing.  I thought the iPad was having problems connecting to the mesh, but actually if I type the IP address 192.168.7.165 into Safari on the iPad I get the portal window.  It is just not "captured".

And I tried to include a psinfo here.  I followed the documentation in the Wiki, got the psinfo.txt on the desktop, but it turns out I did not have write access to the usb drive.

**Comment by haxwithaxe** [comment]
1) wow ...
2) what does the ipad say the issue is?
3) is the browser trying to navigate someplace on it's own?
4) i'll add a issue to make instructions for submitting psinfo without write access to disks. please check out  the issue i'm going to post a question there for you.
issue #167

**Comment by starbits** [comment]
re: question 2 above:  The iPad does not seem to have an issue.  First I connect to the mesh.  Then, when I start Safari, I get the page I last saw, from the last time I used the iPad.  If I navigate to a website, say google.com, I get "the internet is not available" (or something close to that).  If I navigate to 192.168.7.165 I get the web page running under Byzantium, and can see the services I enabled on the laptop.

**Comment by haxwithaxe** [comment]
the first page you see is almost certainly cached and the lack of internet connectivity makes me think it's probably not getting a gateway address from the dhcp server or it's not recognizing the gateway address, or it isn't getting a correct gateway address.
the 192.168.x.x addresses are on the mesh network and as a client you should get a 10.x.x.x address and a 10.x.x.1 address as your gateway.
what are the ip address and gateway address the ipad has when you try to connect?

**Comment by jimsky7** [comment]
We started up two Byzantium nodes. Same issue here with iPad and MacBook. Cached page, or blank page in one case, come up when Safari launched. Let them sit about a minute and nothing happens. However, on the iPad, -just once- it opened the Byzantium welcome page (with click "OK" to see services). On the MacBook we got no automatic welcome, but were able to connect to the Byzantium chat service by typing the IP address of the service, and when we were in the same subnet. When these devices were wi-fi'd to a different node (meaning in a different subnet on the 10-net), not the one hosting the services, they got message "No services found in the network. Please try again in a little while." I had assumed that the services running on a node could be discovered from any other node, but we tried a couple of configurations and the computer could only see the services when in the same /8 subnet as the services.

**Comment by jimsky7** [comment]
More detail. We started up "node one" and fired up the chat service. We connected an iPad and a Macbook by wi-fi, and used the services just fine. We started up "node two" and got several messages "captive_portal.py failed" when configuring. We then reconnected our Macbook to this second node -- meaning we got DHCP assignment in the same /8 subnet as the second node. When we attempted to access the chat service we got the message "No services found in the network. Please try again in a little while" and could not connect to the web services.

**Comment by haxwithaxe** [comment]
there is a problem with the avahi script so it doesn't discover services in 0.2a.
the macbook thing is weird. if it can get into the network its' MAC address is in the captive portal's firewall rules. the captive portal should only be seen once per device (or per MAC. if there is MAC spoofing going on it won't know any better).
if you use the IP address of node#1 it should go through if it's made it through the captive portal

**Comment by haxwithaxe** [comment]
if you can post the errors you get in attachments or code markdown (```code here```)
`code here`

that would be handy
