### ISSUE TITLE
python build script

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#169]
make a script to rebuild all included python modules for arbitrary python versions, if it doesn't already exist.
handy tool not a big deal if it isn't there.

**Comment by virtadpt** [comment]
I think that should go into a script that builds all of the packages prior to addition to SVN, like we discussed tonight.

**Comment by haxwithaxe** [comment]
perhaps we should try using "pip install --target <fakeroot> <py module>" ?

**Comment by virtadpt** [comment]
In conjunction with virtualenv to sandbox apps and their dependencies to separate directories under /opt.  It's been very effective and surprisingly easy to accomplish.  I have a page on the dev wiki on how to do it in a generic fashion, and it's emminently scriptable (though the environment variables that env/bin/activate sets up probably don't play nicely with Makefiles).
