### ISSUE TITLE
Error on KDE desktop

### ISSUE THREAD

**Issue by ghost** [Byzantium/Byzantium#172]
Hi,

V0.2a, on a standard boot from CD, using the KDE desktop, i receive an error:

Error -KDesktop
could not start process  unable to create io-slave:
Klauncher said:.    OK

This happens on a regular basis, but does not happen with the other LXDE Desktop option.

I am guessing this is a video driver problem?

Setup:
AMD FX Quad 4100
ATI Radeon 4670pcie
Gigabyte GA 970A-D3 F10
4GB RAM
LG DVD RW sata
Asus Wifi pci
etc...

Scott

**Comment by haxwithaxe** [comment]
That release has a race condition that manifests when booting from CD. loading python and X at the same time causes X to timeout while waiting to read from the CD.
ref #118
