### ISSUE TITLE
Byzantium Suggestions

### ISSUE THREAD

**Issue by ghost** [Byzantium/Byzantium#173]
Hi,

If you guys have time to add programs in the next version, can i suggest the following:

VideoLAN: stream video may be more useful that the micro-blog which is broken

BitCoin or similar when a internet connection is found on the network

Or am i asking for too much?

**Comment by haxwithaxe** [comment]
given our use case is just after a natural disaster or nonadversarial human fubar for v1.0 BitCoin might not be a terribly useful addition prior to v2.0. from what we saw when we were up in NYC helping out after sandy Byzantium would fit in a temporary 2-3 day window between nothing and a more robust and permanent solution. VLC (my favorite media player btw) might be worth adding for v1.0 but in the next version (v0.4a) we're working on getting Luci working as the control panel and stuff that works for the microblog and chat systems (status.net would require a bunch or patches to make it work in our network environment).
not too much just needs to get pushed off into the right slots :)
i'm going to split this into two tickets 1 for VLC and one for BitCoin.

**Comment by virtadpt** [comment]
Haxwithaxe has split this ticket into #174 and #175.  Closing this ticket for that reason.
