### ISSUE TITLE
VLC package

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#174]
request in #173 for VLC as a streaming media client/server.
suggest inclusion for 1.0 or sooner.

**Comment by jimsky7** [comment]
I kind of like the idea of VLC as we might be in a position to have video clips that would be important to get out of a disaster area. I think the chances are slim, but finite. Say a 10% chance.

More likely that bandwidth would be cramped and that would restrict any possible video flow. But a picture says 1000 words, so photos and possible video might be very useful.

-Sky

**Comment by haxwithaxe** [comment]
within the mesh bandwidth is likely to be relatively good. mesh to internet won't likely be as good if it's there at all in the first couple days.
video also doesn't need to be HD to be helpful :P
there are also ways to share video or other files without using wireless tech, such as sneakernet or cat5 clotheslines.

**Comment by virtadpt** [comment]
We already package Mplayer (subtype: Gnome UI) and Noatun (KDE's media player) because they're part of Porteus Linux.  I don't know how functional they are.  It might be a better use of development time and disk space to add whatever libraries are necessary to bring them up to part with VLC.  Let's test them and see what we already have.

**Comment by Sitwon** [comment]
Mplayer and VLC both use the same libav backend for decoding and playback,
so anything that Mplayer can decode VLC can decode (and vice versa). Where
you might see a difference is if VLC is statically compiled against a
specific version of libav that was built with different compile-time
options.

**Comment by virtadpt** [comment]
Won't fix - that functionality already exists as Gnome Mplayer/SMplayer/avidemux2, which come pre-installed with Porteus v2.0 and use the same back-ends.
