### ISSUE TITLE
dnsmasq needs custom config file added to final package.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#18]
The customized dnsmasq.conf file in Byzantium/porteus/dnsmasq needs to be put in the final .tgz package.

**Comment by haxwithaxe** [comment]
this should be made a part of the slackbuild as a patch to the original config.
@virtadept: provide location of the custom config so that psypete can set that up please.

**Comment by virtadpt** [comment]
The custom config file is: Byzantium/porteus/dnsmasq/dnsmasq.conf
