### ISSUE TITLE
Live USB on a Mac Mini

### ISSUE THREAD

**Issue by Jental** [Byzantium/Byzantium#184]
Machine: Intel-based Mac Mini (First)
Problem: operation system not loads.

Bootable flash for a mac computer was created using this manual :
http://studyblast.wordpress.com/2011/08/14/guide-mac-os-x-lion-how-to-boot-a-linux-live-system-from-a-usb-drive-how-to-update-any-ocz-ssds-firmware/
After this I copied contents of an image file to the root of the flash drive (not to /efi/boot/) and run /boot/win_start_here.hta (just in case).

So on the flash drive I had following file structure:
/
/efi/
/efi/boot/
/efi/boot/bootIA32.efi
/boot
/boot/...
/porteus/
/porteus/...
/byzantium.pubkey
/INSTALLATION.txt
/packages.txt
/README.NOW
/README.txt
/RELEASE_NOTES.txt
/THANKS.txt
/USB INSTALLATION.txt

Loading of the system stopped after grub loading (no errors were shown).
To load system I needed to ecxecute dollowing commends:
  set root=(hd0, msdos1)  # (hd0) is my flash drive
  linux /boot/vmlinuz
  initrd /boot/initrd.xz vga=F00 changes=/proteus/ # I took this line from a /boot/proteus.cfg file

After that system loaded successfully.

**Comment by singerng** [comment]
I had the same problem on a MacBook Pro - it worked when I burned Byzantium to a CD.  I think it's an EFI problem.

**Comment by haxwithaxe** [comment]
win_start_here.hta will only work on windows. the lin_start_here.sh is much more likely to work though we don't have any iThings to test with so we have a really poor ability to debug issues with apple products at the moment.
macs have issues booting from USB but there was a guy at HacDC the other day who managed to figure it out but we were too sleep deprived to get it in writing :P

**Comment by Jental** [comment]
I've created live-usb flash drive on ma windows machine, so I'm using win_start_here.hta

And about a problem...
I think there are two possible sources of the problem:
- Mac computer loads EFI, located in /efi/boot/ folder and then load GRUB installed into it. GRUB not finds it's config and opens console.
  I'll try to place correct grub.cfg into /efi/boot/ folder and try to lanch system.
- win_start_here.hta works incorrectly
  during process it writes:

Setting up boot record for F:, wait please...
Accessing physical drive: ╬Єърчрэю т фюёЄєях. (// I think it is "Permission denied")
Did not successfully update the MBR; continuing...
Disk F: should be bootable now. Installation finished.

**Comment by Jental** [comment]
I placed a grub.config file into /efi/boot/ directory on my flash drive, and now system loads.
Here is my grub.cfg: http://jental.name/grub.cfg
Originally it was generated for my arch, but I slightly modified it to load Byzantium.

**Comment by jbshirk** [comment]
I am going to try this method on a MBP Santa Rosa (DVD drive is broken). 
http://unix.stackexchange.com/questions/57964/booting-ubuntu-from-usb-on-a-mac
It just needs an ISO on the USB drive. boot holding alt-option key. I will update when the torrent is finished downloading.

UPDATE: the above got me to a GRUB prompt, so clearly that was found in the ISO. 
UPDATE: I put Jental's grub.cfg file in /efi/boot/ but no effect.

**Comment by SevenBits** [comment]
My tool, [Mac Linux USB Loader](https://github.com/SevenBits/Mac-Linux-USB-Loader) may be able to help you. It is designed to boot Linux via USBs on Macs. Just give it the Byzantium ISO file and see if it works for you.

**Comment by jbshirk** [comment]
I'm stuck with Tiger without a reasonable upgrade path (which is why I
want to replace it with linux). :(

**Comment by SevenBits** [comment]
Ah...!

**Comment by virtadpt** [comment]
I may have figured out a solution - making a hybrid .iso and putting it onto a flash drive works on later model Macbooks.

The command `isohybrid byzantium-v0.3a.iso` results in an .iso image that can be dd'd onto a USB key.  Plug it into the machine while it's powered off, hold down the Option key, and turn on the power.  Select the "Windows" drive on the far right - that'll be the Byzantium Linux USB key.

**Comment by virtadpt** [comment]
So, I've been using `isohybrid` on the RC .iso images and we've been testing them on our Macbooks, and it works like a charm.  dd the hybrid .iso image onto a USB key and boot off of it.

This is going to be in the release of v0.3.2a.

**Comment by jbshirk** [comment]
I'd like to try this out on my MBP3,1 2008 (Santa Rosa). Can you point to specific instructions, starting with the proper download? Thanks.

**Comment by virtadpt** [comment]
Download the latest release candidate from here: http://project-byzantium.org/downloads/v0.3.2a/

The filenames are in YYYYMMDD-HHMM format.  You want the ones with 'hybrid' in the filename, because those are hybrid .iso images bootable on Macs.  You'll also need a USB key that you don't mind blanking.

Write the hybrid .iso onto the USB key: sudo dd if=byzantium-v0.3.2a-hybrid-RC-YYYYMMDD-HHMM.iso of=/dev/usbkey bs=1M

Plug the USB key into your Mac and reboot while holding down the Option key.  When you're presented with the drive menu, cursor over to the one that says "Windows" and hit the Enter key.  You'll be presented with a Porteus v2.0 boot splash screen - hit the Enter key again to start the boot process.

You can also download any of the .iso images in that directory, burn them to optical disks, and boot from them.

**Comment by jbshirk** [comment]
one small modification:

... bs=1M
dd: bs: illegal numeric value

change to:
... bs=1024

**Comment by jbshirk** [comment]
Update:

Starting legacy loader
 Using load options 'USB'
 Error: Not Found returned from legacy loader
 Error: Not Found from LocateDevicePath (repeats 10 x)
 Error: Load Error while (re)opening our installation volume

 The firmware refused to boot from the selected volume. Note that external
 hard drives are not well supported by Apple's firmware for legacy OS
booting
- Hit any key to continue*
  ......
  nitpick: actually the rEFInd says 'Legacy' not 'Windows'

**Comment by virtadpt** [comment]
So dd on OSX handles specification of sizes differently?  Didn't know that, thank you.

You're using rEFIt and not the stock boot loader?  Does rEFIt override powering on with the Option key held down?

**Comment by jbshirk** [comment]
every piece of advice I've read on the subject of booting linux on a mac
says install rEFIt. I installed rEFInd, which is the revival of the
defunct rEFIt project. What I do know is that holding Option goes to
"boot EFI" which has only one option that leads to the exact same menu
as if you don't hold Option. I have never seen what happens when holding
Option with the stock boot loader. Do you suggest uninstalling rEFInd?

**Comment by SevenBits** [comment]
To be perfectly honest, Linux has reached the point now that if it doesn't boot from USB using the default boot manager on Macs, then it probably won't work with rEFInd. Even though rEFInd can boot USBs without an EFI loader, that won't improve their compatibility or chance of success of actually booting.

To be honest, rEFIt/rEFInd is totally useless until you go to install Linux on a Mac, in which case it helps with dual or triple booting.

**Comment by jbshirk** [comment]
I uninstalled rEFInd and this is the result: holding Option brings up
the Boot EFI icon, whereupon selecting it, only OS X is visible. At
least rEFInd saw the porteus image on the USB. I did verify that after
starting OS X, the porteus filesystem is readable. So I don't know,
maybe this was a step backward, but some information was gained. I'm at
full stop now. I may have to look into borrowing a USB CD drive or maybe
Net Booting.

**Comment by SevenBits** [comment]
Do you mean that when you select the EFI Boot icon, it boots OS X? If so, the actual boot loader on the USB may well be corrupt or invalid for your architecture. Running Linux on a Mac is something I've been looking into too; my tool, Mac Linux USB Loader, is designed to do just this. Unfortunately, booting via EFI is so flaky. Until somebody thinks of a solution, I'm afraid you'll need to boot from a DVD. I highly recommend Apple's OEM DVD readers - they're great as a fallback for this purpose.

**Comment by jbshirk** [comment]
I know there are disc errors; the reported space available exceeds the
total space and all my attempts to resize partitions have ended in error
and failure. The heroic attempts to keep this machine useable are
starting to make me weary.

:) no way am I going to buy an Apple OEM DVD just to get apple out of my
life. I'm in Brazil where macs are not too common, but hopefully I can
borrow one.

**Comment by virtadpt** [comment]
@jbshirk Did you try to boot Byzantium from a USB key or optical disk?  Did you use the hybrid .iso image, or the regular .iso image?

**Comment by jbshirk** [comment]
I am restricted to USB; my built-in superdrive doesn't work. I used the
hybrid image as recommended.
