### ISSUE TITLE
DNS Non-53 Port 

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#192]
our fake dns for the captive portal is responding from it's native port and not 53. dns-spoofing countermeasures pick it up as malicious so we need to fix it to respond via port 53.
iptables based sollution was mentioned.

**Comment by virtadpt** [comment]
It may not be possible or feasible to fix this for everyone.  I know that I've got a couple of plugins in my browsers that keep this sort of thing from happening, but then again I'm a paranoid edge case.  It might wind up being more trouble than it's worth to deal with people like me - if nothing else it would complicate things under the hood a great deal.

That said, there may be a way of rewriting packets sent by fake_dns.py so they look like they came from port 53/udp:

```
iptables -t nat -A POSTROUTING -d 10.x.y.z/24 -p udp --sport 31339 -j SNAT --to-source :53
```

Source: http://serverfault.com/questions/283137/iptables-to-modify-all-source-ports-to-1-single-source-port

**Comment by virtadpt** [comment]
Added rules to rewrite replies from the captive portal daemon in commit 3860d4fa3d1c269016cbdf0d967faf41efcf5ebe.

**Comment by virtadpt** [comment]
Tested, it works.  We have to patch the HTML redirect from captive_portal.py, which is a separate issue.
