### ISSUE TITLE
broadcom-sta can't set bssid

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#195]
broadcom-sta driver complains and can't manually set bssid.
if other devices with the same essid and correct bssid are present during boot it will use the correct bssid.
i'm pursuing (http://basiclinuxtips.blogspot.com/2012/01/broadcom-b43xx-driver-install-for.html) as a possible means to fix this as it appears to be applied to a card requiring broadcom-sta.

**Comment by haxwithaxe** [comment]
the above is a fail.

**Comment by virtadpt** [comment]
We have a couple of potential solutions here (which we should detail in subsequent comments on this ticket).  It's a fairly small number as I recall so we should be able to brute-force that solution space in a fairly shortly period of time.

**Comment by virtadpt** [comment]
Links that Sitwon posted in IRC earlier (and reposted again - thanks!)
- http://wireless.kernel.org/en/users/Drivers/b43
- https://help.ubuntu.com/community/WifiDocs/Driver/bcm43xx

**Comment by virtadpt** [comment]
b43 firmware (http://slackbuilds.org/repository/14.0/network/b43-firmware/) is already in 000-byantium.xzm.

wl.ko is already in Porteus v2.0.

This is relevant to our interests: http://forum.porteus.org/viewtopic.php?f=39&t=1099

By default, /etc/modprobe.d/b43_blacklist.conf contains the following:

`blacklist b43
blacklist b43legacy
blacklist bcma
blacklist ssb`

In Byzantium, we replace that file with an empty one.

I just built a new module and built a new RC .iso image.  It's up for download.  I haven't tested it yet.

One of three things might happen: The Broadcom cards that worked before now don't, and the ones that didn't now do.  No Broadcom cards work now.  Or they all work now.  Let's find out.

**Comment by virtadpt** [comment]
I just followed the directions in the article that @haxwithaxe linked to (which describes how to use b43-fwcutter to extract the firmware images from OpenWRT's b43 driver) and built another pair of RC .iso images.  They're up now.
`byzantium-v0.3.2a-[hybrid-]RC-20130508-2146.iso`

I've also just put up a version that has the new firmware images and an empty b43_blacklist.conf file.
`byzantium-v0.3.2a-[hybrid-]RC-20130508-2153.iso`

**Comment by virtadpt** [comment]
I just tested byzantium-v0.3.2a-hybrid-RC-20130508-2153.iso on my Macbook.  It works as expected, i.e., the Broadcom wireless card that worked before still works with the OpenWRT firmware images installed.

**Comment by virtadpt** [comment]
@haxwithaxe reported that the RC's I posted last night didn't work. He also mentioned that he tried a bit of symlink jiggery-pokery in `/lib/firmware` that did unusual things.  I dug into the test fakeroot I built last night, and discovered that my Porteus v2.0 VM has a very different set of firmware images from Byzantium Linux... because I have the 'official' kernel-firmware package installed.  Diffing the contents of `/lib/firmware` before and after revealed that the firmware collection was half as large after I deactivated the kernel-firmware package.

I've built two new RC .iso images that have the kernel-firmware image included:

byzantium-v0.3.2a-RC-20130509-0946.iso
byzantium-v0.3.2a-hybrid-RC-20130509-0946.iso

**Comment by virtadpt** [comment]
@Sitwon and I went digging around in the kernel config file for Porteus v2.0.  He suggests recompiling the b43 module with the CONFIG_B43_BCMA_EXTRA option turned on.  This means that we don't have to recompile the entire kernel, just the modules in question, and we can splice them into 000-byzantium.xzm.

**Comment by virtadpt** [comment]
Used this procedure to compile a new kernel: http://www.porteus.org/component/content/article/20-tutorials/development/91-compilation-and-usage-of-custom-porteus-kernel.html

**Comment by virtadpt** [comment]
Bug report and request filed in Porteus Linux forums: http://forum.porteus.org/viewtopic.php?f=41&t=2182
