### ISSUE TITLE
Commotion route isn't installed.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#198]
The autoconfiguration daemon (byzantium_configd.py) does a pretty good job of enumerating and configuring wireless interfaces, but for reasons as yet unknown it fails to install the Commotion Wireless compatibility route (5/8) on detected wireless interfaces.  It seems to be reproducable on every boot, and it can be verified by running the `route -n` command as the root user.

**Comment by haxwithaxe** [comment]
this is likely due to the fact that it isn't seeing any 5/8 hosts. if there isn't a host then not any point having a route to it.

**Comment by virtadpt** [comment]
If you set up the route manually, though, it sticks (and works).  That's what we did in New York.

**Comment by virtadpt** [comment]
Fixed in commit ba08ddd70d48680badcf4512fe1a3a040e9ee34f.
