### ISSUE TITLE
Deactivate debugging output from captive portal daemon.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#199]
captive_portal.py does an excellent job of implementing a captive portal for mesh users, but it makes debugging other things problematic because it prints a set of stats to the console once every minute or so.  This causes things like system logs and periodic outputs (e.g., the output of the `watch` command) to either scroll off the top of the screen or become otherwise corrupt.

Can this debugging output be hooked to a command line switch so it's not on by default?

**Comment by haxwithaxe** [comment]
we can do that. i can stick the debug output in a debug function if it isn't already and have it output to a file when it's launched with --debug.

**Comment by virtadpt** [comment]
Excellent.

**Comment by virtadpt** [comment]
That's already done.  Nevermind.
