### ISSUE TITLE
Control panel doesn't put the wireless interface into ad-hoc mode.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#2]
The network configuration application of the control panel never actually puts any wireless interfaces into ad-hoc mode.  If you run iwconfig on a wireless NIC, it shows that it's stil in managed mode.  This breaks mesh networking completely.  Oops.

**Comment by haxwithaxe** [comment]
know problem
check to see if it's made the change and keep trying until it sticks

**Comment by haxwithaxe** [comment]
also get back on irc and i can help faster :P

**Comment by virtadpt** [comment]
Acknowledged.  Fixed in my private checkout, re-copied on my development machine and tested.  Pushed up to Github:

To git@github.com:Sitwon/Byzantium.git
   90fcdb5..1bc7505  master -> master

**Comment by virtadpt** [comment]
I used a fix that checks the wireless configuration over and over until it stabilizes, and only terminates when it's made a complete circuit of the output of iwconfig and everything looks good.

**Comment by virtadpt** [comment]
When testing the v0.1a build prior to release the wireless chipset in my test machine got cranky again, and its configuration had to be set manually because it didn't take from the control panel.  I don't know if this is a code problem, or if it's a problem with my test machine.  Here are the system specs (from the HCL):

Asus EeePC 900
    Atheros AR5001 rev. 01 wireless chipset
    Atheros L2 Fast Ethernet rev. a0 ethernet chipset 

Is anyone else seeing this?

**Comment by virtadpt** [comment]
First, see commit 3b27d8c7daca5e063e4c317b2db204ad007d3705.

After doing this, putting wireless interfaces into ad-hoc mode on my test machines was flawless.  Also, when the Zero State team built PubMesh a few weeks ago they never mentioned running into this problem.  I'd call this closed.
