### ISSUE TITLE
Localhost:8080 Not found in mac live cd

### ISSUE THREAD

**Issue by conbdevaca** [Byzantium/Byzantium#203]
Hi!
I just downloaded the 0.3v and when starting byzantium and typing localhost:8080 nothing happens, it says: "unable to connect", im testing it in a macbook pro in VESA mode.
tried with the 0.2 v and even if it connects to localhost:8080 it just gets hanged when setting wireless network parameters.
Thank you so much! keep going!

**Comment by virtadpt** [comment]
http://localhost:8080/ used to connect to the control panel.  We got rid of the control panel in this release.  It was replaced with an autoconfiguration daemon.  This also means that the network applications in the image are "always on."

This is what we meant when we said that this was a formalization of a field deployment- that was our use case at the time.
