### ISSUE TITLE
ngircd package build fails.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#21]
The exact error message is "configure: error: Can't enable gnutls".  When I built the existing package by hand I had to pass the switch --disable-gnutls to ./configure for the build to go through.

**Comment by haxwithaxe** [comment]
@psypete: can you figure out whether gnutls is required and either add a gnutls package or adjust the ngircd.SlackBuild to fix this.

**Comment by virtadpt** [comment]
Suggest adding the switch --disable-gnutls to the invocation of configure because there are potential functional conflicts between OpenSSL and GnuTLS.  At least, that's how I got it to build manually during R&D.
