### ISSUE TITLE
Mesh network visualization

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#217]
We need to fix the mesh network visualization (virtual connection map) and make sure that's one of the first things people see when their node joins the network successfully.

ISC Milestone 4 Priority #5

**Comment by joncamfield** [comment]
It'd also be nice to see a list of the services you're providing from your node (IRC, pad...) -- or have that as part of the visualization itself.

**Comment by virtadpt** [comment]
That would have to be a separate bit of functionality.  We have a networking mapping application already which talks to the routing daemon and figures out the map from its diagnostic port.

**Comment by Sitwon** [comment]
I like that idea. Might not make it in to this release but we should definitely keep it on the back burner. It would be useful for knowing which is the closest node providing a particular service for you to connect to.

**Comment by virtadpt** [comment]
It might be worth investigating whether or not we could add that functionality to olsr-viz.

Or, thinking about it a bit, the back-end code for olsr-viz is just a shell script that uses wget to pull data out of olsrd (http://localhost:2006/).  We could probably extend that script by pulling information out of Avahi's service database and annotate what it draws further.

**Comment by virtadpt** [comment]
The network visualizer works now.  If there is more than one node the display populates because olsrd is generating connection metrics at that point (it can't generate metrics for itself).
