### ISSUE TITLE
Responsive Web Design Everywhere

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#218]
We need to audit all our pages to make sure that we're using responsive web design. This is essential for mobile clients like Android and iOS. 

ISC Milestone 4 Priority #6

**Comment by virtadpt** [comment]
- Captive portal pages
- Dynamic service directory

**Comment by virtadpt** [comment]
```
find /tmp/fakeroot -type f -name '*.html' -print
```

**Comment by virtadpt** [comment]
We know that Groundstation's mobile-friendly.

Etherpad-Lite has some stuff in its HTML templates which appear to be similar to the responsive CSS stuff you added, Sitwon.  We should still try it with a couple of mobile browsers.

[pass,fail].html are only viewable from the node's desktop, so those are as optimal as they can be.  Same with olsr-viz-lite.

The dynamic service directory stuff needs it, but it's not ready yet.  It should be easy to splice it into the HTML.  I'll fork() a copy of that repo and add it.

**Comment by virtadpt** [comment]
Added to haxwithaxe/python-byzantium/opt/byzantium/service_index/templates/ and issued pull request.

**Comment by virtadpt** [comment]
I don't know if QwebIRC is responsive or not.  The HTML templates are pretty dense, and most of the functionality is JavaScript to begin with, so we might have to test it with a mobile to see.

The docs say that it can be themed, so it should be possible to add it if it's not already.

**Comment by haxwithaxe** [comment]
#219 #218 
web.py is being used to implement the web front ends and takes to bootstrap just fine.
there is a byxantium.view.web module (in byzantium/python-byxantium) with prototypes for several types of pages.

**Comment by virtadpt** [comment]
I created a temporary account on browserstack.com and played around with Freenet's QwebIRC instance.  It's responsive, or as responsive as IRC gets.
