### ISSUE TITLE
Compilation of git Porteus module doesn't work.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#22]
Using the build-o-matic to compile a Porteus module of Git doesn't work.  It fails due to the for... loop in build.sh.  Executing the package construction process by hand omitting the for.. loop almost works.  It dies at the end of the ./configure process with the following error:

...
checking for library containing mkstemps... none required
checking for initgroups... yes
checking for library containing initgroups... none required
checking Checking for POSIX Threads with '-mt'... no
checking Checking for POSIX Threads with '-pthread'... yes
configure: creating ./config.status
config.status: creating config.mak.autogen
./git.SlackBuild: line 96: /etc/profile.d/32dev.sh: No such file or directory

32dev.sh doesn't seem to exist in the test VM.  Running a find(1) as root on / doesn't return anything.

**Comment by haxwithaxe** [comment]
double check this with the new build.sh and then assign it to psypete or me if it still doesn't work

**Comment by virtadpt** [comment]
The build.sh script chokes on comments in the foo.info files.  Deleting the comments allows the build process to proceed past the for... loop.

As for the git module, the compilation process dies here:

[output of ./configure omitted...]
configure: creating ./config.status
config.status: creating config.mak.autogen
git.SlackBuild: line 96: /etc/profile.d/32dev.sh: No such file or directory
make[1]: **\* [../pkgs/git-1.7.4.4-i486-1.tgz] Error 1
make[1]: Leaving directory `/home/guest/Byzantium/porteus/git/src'
make: **\* [pkgs/git-1.7.4.4-i486-1.tgz] Error 2
root@byzantium:/home/guest/Byzantium/porteus/git#

**Comment by virtadpt** [comment]
From git.SlackBuild:

export CC=/usr/bin/32/gcc
. /etc/profile.d/32dev.sh

This isn't needed.  For Porteus, GCC is called as /usr/bin/gcc.

**Comment by haxwithaxe** [comment]
build.sh updated to ignore whole line # comments

**Comment by virtadpt** [comment]
Fixed git.SlackBuild to get around library errors.  Now dies because it can't find asciidoc:

make[4]: `GIT-VERSION-FILE' is up to date.
make[4]: Leaving directory`/tmp/git-1.7.4.4'
make[3]: Leaving directory `/tmp/git-1.7.4.4/Documentation'
make[3]: Entering directory`/tmp/git-1.7.4.4/Documentation'
    CC blob.o
    CC branch.o
    CC bundle.o
    CC cache-tree.o
make[4]: Entering directory `/tmp/git-1.7.4.4'
make[4]:`GIT-VERSION-FILE' is up to date.
make[4]: Leaving directory `/tmp/git-1.7.4.4'
    CC color.o
    ASCIIDOC git-tar-tree.html
    CC combine-diff.o
/bin/sh: line 1: asciidoc: command not found
make[3]: *** [git-tar-tree.html] Error 127
make[3]: Leaving directory`/tmp/git-1.7.4.4/Documentation'
make[2]: **\* [doc] Error 2
make[2]: **\* Waiting for unfinished jobs....
make[2]: Leaving directory `/tmp/git-1.7.4.4'
make[1]: *** [../pkgs/git-1.7.4.4-i486-1.tgz] Error 1
make[1]: Leaving directory`/home/guest/Byzantium/porteus/git/src'
make: **\* [pkgs/git-1.7.4.4-i486-1.tgz] Error 2

**Comment by virtadpt** [comment]
This was changed to "use whatever copy of git your build environment will support," and is thus a non-issue.
