### ISSUE TITLE
Compilation of Tor module ABENDs.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#25]
Compilation of the Tor Porteus package fails like the others have due to the for.. loop in build.sh.  Here's the error message:

...
../../build.sh: line 8: export: `#': not a valid identifier
make[1]: *** [../pkgs/tor-0.2.2.32-i486-1_SBo.tgz] Error 1
make[1]: Leaving directory`/home/guest/Byzantium/porteus/tor/src'
make: **\* [pkgs/tor-0.2.2.32-i486-1_SBo.tgz] Error 2

I had to tweak the build files a little bit to pull v0.2.2.33 rather than .32 because the latter isn't available at distfiles.gentoo.org anymore.  The script dies in a different way:

./tor.SlackBuild: line 99: LD_LIBRARY_PATH: unbound variable

Compilation of libevent succeeds, though.

**Comment by haxwithaxe** [comment]
set LD_LIBRARY_PATH to '/lib:/usr/lib/usr/local/lib:/usr/i486-slackware-linux' (if i486-slackware-linux doesn't exist then omit it or replace it if i486-porteus-linux exists)
also try the build.sh again now that it's been fixed

**Comment by virtadpt** [comment]
Had to delete the comment from tor.info to get past the initial tests.

Build fails with:
tor.SlackBuild: line 94: cd: /tmp/SBo/package-libevent/usr/lib: No such file or directory
make[1]: **\* [../pkgs/tor-0.2.2.33-i486-1_SBo.tgz] Error 1
make[1]: Leaving directory `/home/guest/Byzantium/porteus/tor/src'
make: **\* [pkgs/tor-0.2.2.33-i486-1_SBo.tgz] Error 2

**Comment by virtadpt** [comment]
Deleted pkgs/libevent-2.0.10-i486-1_SBo.tgz, tried again from square 0.  Died in the same way.

export LD_LIBRARY_PATH='/lib:/usr/lib/usr/local/lib:/usr/i486-slackware-linux'

Re-ran build.  Died with the following error:

checking for libevent directory... configure: WARNING: Could not find a linkable libevent.  If you have it installed somewhere unusual, you can specify an explicit path using --with-libevent-dir
configure: error: Missing libraries; unable to proceed.
make[1]: **\* [../pkgs/tor-0.2.2.33-i486-1_SBo.tgz] Error 1
make[1]: Leaving directory `/home/guest/Byzantium/porteus/tor/src'
make: **\* [pkgs/tor-0.2.2.33-i486-1_SBo.tgz] Error 2

Modify clean: stanza of Makefile to delete /all/ of the stuff built for a particular package (in this case, the libevent package)?

**Comment by haxwithaxe** [comment]
perhaps "dist-clean" or however it's spelled?

**Comment by virtadpt** [comment]
There does not appear to be such a stanza at present in the Makefile.  I've been going through all of the sub-directories for a particular package and erasing the tempfiles and existing packages (as well as the stuff that winds up in /tmp/SBo).

Just did a `git pull` and a test build - no soap.

tor.SlackBuild: line 99: LD_LIBRARY_PATH: unbound variable
make[1]: **\* [../pkgs/tor-0.2.2.33-i486-1_SBo.tgz] Error 1
make[1]: Leaving directory `/home/guest/Byzantium/porteus/tor/src'
make: **\* [pkgs/tor-0.2.2.33-i486-1_SBo.tgz] Error 2

Tweaking value of LD_LIBRARY_PATH in tor.info a bit.  Will check a new copy of the file in if it works, will revert if not.

**Comment by virtadpt** [comment]
Found the following in the temporary build directory:

lrwxrwxrwx 1 root root     21 Oct 18 21:27 libevemt.so -> libevent-2.0.so.5.0.1*

Shouldn't that be this:

lrwxrwxrwx 1 root root     21 Oct 18 21:27 libevent.so -> libevent-2.0.so.5.0.1*

Renamed the symlink manually and got a clean build.  Need to fix this in the build script for libevent.

**Comment by virtadpt** [comment]
Found the bad symlink in Byzantium/porteus/tor/src/tor/tor.Slackbuild.  Fixed.  Retried build.  Success.
