### ISSUE TITLE
Need doxygen to compile apr.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#27]
The APR package will not compile properly unless doxygen is installed beforehand.  I went through the online help in the configure script and there doesn't seem to be a --switch to disable doxygen checks.  We need a doxygen Porteus package as a dependency.

**Comment by psypete** [comment]
compile-time deps should be provided by your dev distro of choice. for porteus as a dev platform you can use slackyd or slackpkg to download & install slackware packages to your dev system.
