### ISSUE TITLE
Need a cmake package.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#28]
The openjpeg part of the Porteus meta-package mupdf won't compile unless cmake is installed.  Error message:

[successful compilation of libjbig omitted...]
[decompression of openjpeg tarball omitted...]
patching file jp3d/libjp3dvm/CMakeLists.txt
patching file libopenjpeg/CMakeLists.txt
openjpeg.SlackBuild: line 76: cmake: command not found
make[1]: **\* [../pkgs/openjpeg-1.4-i486-2_SBo.tgz] Error 127
make[1]: Leaving directory `/home/guest/Byzantium/porteus/mupdf/src'
make: **\* [pkgs/openjpeg-1.4-i486-2_SBo.tgz] Error 2

We need a Porteus package for cmake.  At least we won't have to include it in the final distribution, we just need it as a compilation tool.

**Comment by psypete** [comment]
compile-time deps should be provided by your dev distro of choice. for porteus as a dev platform you can use slackyd or slackpkg to download & install slackware packages to your dev system.
