### ISSUE TITLE
Need module for asciidoc.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#29]
Git won't finish compiling without the presence of asciidoc (http://www.methods.co.nz/asciidoc/), which is used to format its documentation files.  Sauce:

/bin/sh: line 1: asciidoc: command not found
make[3]: **\* [git-tar-tree.html] Error 127
make[3]: Leaving directory `/tmp/git-1.7.4.4/Documentation'
make[2]: *** [doc] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory`/tmp/git-1.7.4.4'
make[1]: **\* [../pkgs/git-1.7.4.4-i486-1.tgz] Error 1
make[1]: Leaving directory `/home/guest/Byzantium/porteus/git/src'
make: **\* [pkgs/git-1.7.4.4-i486-1.tgz] Error 2

**Comment by psypete** [comment]
compile-time deps should be provided by your dev distro of choice. for porteus as a dev platform you can use slackyd or slackpkg to download & install slackware packages to your dev system.
