### ISSUE TITLE
Feature Request: DNSSec

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#30]
add dnssec capabilities for internet connected nodes. this should wait until 2.0 unless we have an opportunity to get it going before then.

**Comment by virtadpt** [comment]
What exactly do you mean by this?

dnsmasq isn't capable of verifying digital signatures for DNS zone information, but it is capable of proxying those requests (and responses thereto) out of the box, it just needs an extra command line flag when it starts up.  dnsmasq also doesn't support DNSSEC for zones it's authoritative for (which means the IP subnet that Byzantium node is responsible for).  There isn't a CA for the domain byzantium.mesh, and if we turn every node into a DNSSEC CA for byzantium.mesh, it'll probably make a dog's breakfast out of everything unless we partition that domain (foonode.byzantium.mesh), but then we'd run into the problem of having a top-level DNS for byzantium.mesh, and it goes around and around in circles again...

**Comment by haxwithaxe** [comment]
this was proposed by someone in the comments of the make post as something that would act on the internet to mesh connection and not within the mesh. also this is for the 3rd full version so no need to worry about this now.

**Comment by virtadpt** [comment]
This can be done by adding the CLA --proxy-dnssec when dnsmasq is started up.  The thing is, the manpage also says that you have to explicitly trust the upstream DNSes to not be playing games, and in the Egypt Scenario you can't do that. In other words, it won't actually make things more secure, but could potentially make users whose traffic is being gatewayed to the Net less so.
