### ISSUE TITLE
Control panel: split PID getting code into a helper method.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#35]
In MeshConfiguration.enable() split the code that grabs the PID of babeld into a separate method.  In the long run it'll make the code easier to maintain, as well as making it easier for us to switch to a different mesh routing protocol if we decide to do so in the future.

**Comment by shanel** [comment]
I did this in my latest merged commit.

**Comment by Sitwon** [comment]
Fixed in 725e952
