### ISSUE TITLE
Logging and system seizure.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#4]
In use cases like the Egypt Problem, it is likely that a Byzantium node, if seized, could be analyzed to gather information about currently associated users.  Thus, it would be prudent (after the alpha release) to configure the system and as many apps as feasible to either log nothing (best case) or log directly to /dev/null (worst case).

It would also help prevent nodes from running out of disk space (and RAM, in the case of liveboot-only nodes).

syslogd should be disabled.  Apache should be configured to log nothing.  MySQL error logging should be turned off.  Etherpad-Lite should log nothing.  The IRC server should be confirmed to log nothing; logging of qwebirc should be disabled as well).

**Comment by virtadpt** [comment]
This should probably be linked to ticket #3 because it's specifically described as a secuity issue.

**Comment by Sitwon** [comment]
Most of the existing logs do no contain any sensitive information so they're not much of a concern. From a disk utilization stand point, logrotate should keep things under control.

If anyone finds specific examples of logs that need to be squelched, create a separate ticket for those logs.
