### ISSUE TITLE
Control panel security audit.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#5]
The source code of the control panel (written in Python and using CherryPy) needs to be audited for security vulnerabilities (including HTML vulnerabilities!).  I'm not a webapp.sec guru and I would really like people who are more knowledgable of such things to go through the control panel and double-check my work.  I've tried to trust as little input as I could (preferring input from the OS over user input) but that's nothing compared to somebody who knows this stuff better than I putting it under the microscope.

**Comment by virtadpt** [comment]
I've contacted some old colleagues of mine about this.  They're interested in doing a security audit, but they're busy so I have to ping them periodically about it.  If anyone wants more information, send me an e-mail (encrypted, preferably) and I'll explain.

**Comment by Sitwon** [comment]
Since the control panel is only hosted on the local interface, is this even reasonable attack vector?

**Comment by virtadpt** [comment]
I'm working to pin down $colleagues this week to get them to sit down and take a look at it (they expressed interest in doing so).

Here's the thing: I'm not a web developer.  There are several classes of vulnerability in web applications that I know of but I'm not sufficiently conversant in web application design to know if they apply to the control panel or not.  I'd very much like someone who's better at this sort of thing than I to look at the codebase and make that determination.

**Comment by virtadpt** [comment]
The control panel is obsolete and no longer included, so this is irrelevant.
