### ISSUE TITLE
Request For Comment: Change the 'guest' password to be blank.

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#52]
It currently isn't too obvious that the password for the 'guest' account (the default account) is 'guest'. Someone faced with a password prompt after the screensaver locks the screen might not know what to do. 

I think the options are:
1) Make the password way more obvious at boot time.
2) Make the password blank.
3) Don't lock the screen when the screensaver starts.
4) Disable the screensaver entirely.

Some or all of these are probably a good idea. I don't think having a password for guest really buys us much security so we might as well just not have it. Also, I don't like screen savers so getting rid of that would be fine by me too. 

Thoughts? Comments? Suggestions?

**Comment by virtadpt** [comment]
One of the things I suggested during the September dev sprint was the development of an initscript that changed a bunch of system passwords on first boot (MySQL and /etc/passwd) and then informed the user that the ones they would be using directly (i.e. 'guest' and 'root') of the passwords for better security.

Alternatively, we might be able to go Ubuntu on this and use sudo for everything and lock the root account entirely.

**Comment by virtadpt** [comment]
Locked the root account ala Ubuntu.  Cleared the password on the guest account.  Installed an /etc/sudoers file that allows the guest user to execute commands as root.

Reference: c992029ab3f32362ec4e113efaaf1dbcaf59074a
