### ISSUE TITLE
Always generating an SSL certificate at boot-time is too time consuming to be useful.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#53]
10-20 minutes to boot the first time, plus another 10-20 minutes after the user gets persistent storage set up?  No way.    On the other hand, all of the encrypted services rely on that certificate.  So, what to do?

We could ask the user at some point if they'd like to generate a cert.  The downside is that the SSL/TLS protected services won't start until they do so.

We could pre-generate an SSL cert with an absurdly long lifespan, but that means that all nodes will probably have the same cert, and that's no good.  Anyone could then download Byzantium and use the included cert to decrypt captured traffic.

We modify rc.ssl to detect whether or not the system has enabled persistent storage and only generate the cert if it detects it.  We might amp it off but that means that the encrypted services won't run until it's done, and that makes for a rather poor user experience.

**Comment by Sitwon** [comment]
Alternatively, can we disable the mandatory SSL cert generation at boot-time and instead have a script on the desktop that generates the cert and enables SSL support when the user decides it's appropriate to do so?

**Comment by virtadpt** [comment]
I figured out what the problem was - it's not the SSL cert but the optional Diffie-Hellman parameter generation.  I commented that bit out and the time to run that script was cut by at least an order of magnetude.
