### ISSUE TITLE
Software request: Truecrypt.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#54]
Compile and package Truecrypt (http://www.truecrypt.org/) with Byzantium.

**Comment by alexxxxx** [comment]
To be installed, Truecrypt requires:
wxWidgets source code or  header and shared library installed,
I will investigate in this direction to compile it

**Comment by virtadpt** [comment]
Excellent.  Don't forget to check the PGP signature on the Truecrypt tarball.

Here is the package creation process: http://wiki.hacdc.org/index.php/Processes_for_building_Porteus_packages. (note that there has to be a period at the end of that URL).

**Comment by virtadpt** [comment]
You'll find the following extremely helpful:

http://slackbuilds.org/repository/13.37/system/truecrypt/

http://slackbuilds.org/repository/13.37/libraries/wxGTK/

**Comment by alexxxxx** [comment]
Thanks a lot for the links,

regarding truecrypt, the console mode is enough or you want a graphical
interface?

On Sun, Jan 15, 2012 at 9:40 PM, The Doctor <
reply@reply.github.com

**Comment by virtadpt** [comment]
I think the graphical interface would be a good idea, seeing as how everything else on the node has a GUI.

**Comment by virtadpt** [comment]
The TrueCrypt page at SlackBuilds.org lists the cryptoki SlackBuild as a pre-requisite.  I've added both of them to the Git repo so we know that they're necessary.

Reference commit: 7751ab96b05afef327eaf118647bcb58ec94c521

**Comment by virtadpt** [comment]
wxGTK is a pre-requisite for TrueCrypt because it implements the GUI.  The SlackBuild has been added to the repo.

Reference commit: 3e8946844a076932abe037fbefbf2b36e6d8e722

**Comment by virtadpt** [comment]
TrueCrypt packaged, tested, and added to fakeroot.
