### ISSUE TITLE
Request for comments: Wireless encryption by default.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#56]
It's been suggested to us that we configure the network interfaces to be encrypted by default, i.e., at a minimum picking WEP but WPA may also be an option.  This would help protect OSI layer 2 and above from certain spoofing attacks, as well as adding a thin layer of privacy atop mesh traffic.  If the settings were not standardized (i.e., defaults were not set in the Byzantium configs)  this would stand in the way of ad-hoc deployment (because small cabals of hackers would have to decide on WEP/WPA settings and make sure that everybody within earshot knew about them).  This would also stand in the way of clients connecting randomly to the mesh to make use of it because it would require more knowledge than just seeing "Byzantium" or "Free Mesh Network" or something in the wi-fi control panel of their device.

Frankly, I can't see this being of much use to us.  WEP is trivially easy to break.  WPA is stronger but still crackable by a determined enemy (certainly anyone capable of wanting to take down the mesh in a Egypt Problem scenario) in a reasonable period of time.  It's going to hang up potential users who are conditioned to see padlocked (i.e. encrypted) wireless networks and ignore them because "they don't have the password anyway."

Thoughts anyone?

**Comment by Sitwon** [comment]
I would be inclined to just leave it off by default. As you point out, it doesn't add much protection at the expense of a whole lot of confusion. In the Haiti or Katrina situations there would be little or no benefit but it would probably cause a lot of confusion and problems.

It seems reasonable to want to have _some_ encryption in cases such as Egypt, but would lean toward WEP. As noted, WPA doesn't offer a whole lot more protection than WEP (so if they're going to the trouble of cracking it they will crack it anyways), but I believe there are still several devices (such as phones) that don't support WPA.

**Comment by virtadpt** [comment]
There is also some evidence that in some parts of the Middle East the content of wireless traffic is of less interest in the field than the presence of open wireless access points.  Whether or not a mesh has WEP or WPA enabled may make the difference between a door getting kicked in or hostile field units ignoring what appears to be a personal access point.

We also need to be cognizant of the wireless capabilities of the mobile devices people usually carry in our regions of interest.

**Comment by collina** [comment]
I think the two of you are coming to the correct consensus. Wireless authentication methods will primarily present a difficulty in coordination that will probably be an impediment to usage, especially more so than device support issues. 

As far as baselines, I would suggest that the majority of Byzantium mobile users will be running iOS 3+, Android 1.6+, Blackberry 4.2+ or Symbian S60 3rd Edition+. My belief, informed by a little research, is that all these platforms support WPA. When you get to _WPA2_, you will definitely run into issues with the S60 devices.

**Comment by shanel** [comment]
In an emergency situation you are going to want to get stuff up and running ASAP, so defaulting to off makes sense. In a hostile environment it might make sense to use something like WPA. Seems like there could be two routes here:

1) Default it to being off and when starting up give the option of securing it via WPA but explain the problems and et the admin decide.

2) Bring up both an insecure and a secure network and people can use whichever they want - and the admin has the ability to turn off the one they don't want used. Maybe the captive portal for the insecure one can tell them that there is a secure one they could be using? (Not sure how feasible this one is, but thought I would toss it out there.)

**Comment by virtadpt** [comment]
1) The biggest problem being, getting everyone on the same WPA key at the same time.  Minimizing the need for collusion poses a problem here.

2) That limits the possible size of the mesh.

3) We're considering IPsec in opportunistic mode.  That would apply to everything leaving every node that spins up.

**Comment by Sitwon** [comment]
> 2) Bring up both an insecure and a secure network and people can use
> whichever they want - and the admin has the ability to turn off the one
> they don't want used. Maybe the captive portal for the insecure one can
> tell them that there is a secure one they could be using? (Not sure how
> feasible this one is, but thought I would toss it out there.)

There aren't many cards that can do this. On Linux you might have some luck
with Atheros cards or with Intel cards, but most cards can't operate on two
networks at the same time.

If we had dedicated router hardware with multiple adapters it wouldn't be a
problem, but we're trying to make do with the single built-in adapter as
much as possible.

**Comment by virtadpt** [comment]
After discussion and experimentation, I don't think that this will buy the users much of an advantage, and in fact might prevent a lot of people from trying to use the mesh.  We can mitigate this with transparent encryption higher up in the OSI stack.
