### ISSUE TITLE
Request for comments: Hardcode a BSSID to ensure organic growth?

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#57]
A subtle problem that arose during lab testing was that some ad-hoc nodes (I'm looking at your, Linux v3.0.2!) do not listen long enough for the broadcast BSSID of a mesh and pseudo-randomly select their own, resulting in two meshes that can't communicate with one another.  This is an irritating bug to track down in the field.

It was suggested to Sitwon and I by the Commotion Wireless guys that we pick a BSSID and standardize on it; that's how they fixed this particular problem.  We could pick just about any MAC address-like string and force all mesh interfaces to use it.  It appears that we could do this by incorporating the following command in the control panel's code:

```
iwconfig wlan? ap c:0:f:f:3:3
```

Comments?  Questions?

**Comment by Sitwon** [comment]
I like that one, good choice. :-)

**Comment by Sitwon** [comment]
Fixed with #128
