### ISSUE TITLE
RFC: Public DNSes on gateway nodes.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#59]
When we get gateway (mesh node-to-Internet) functionality nailed down, one of the things we're going to have to contend with is DNS resolution.  On one hand, dhcpcd is probably going to be used to grab configuration information for the mesh node (including the IP addresses of DNS servers for client resolution).  We may not be able to trust that those DNSes are not filtering requests for certain IP addresses, so it would behoove us to decide on a list of public DNSes that can be reasonably trusted to not try anything funny.  Google's are a good start, as are 4.2.2.1, 4.2.2.2, 4.2.2.3, and 4.2.2.4.  There are, in fact, rather complete lists of public DNSes out there that we can harvest from.

The question is, which ones should we "officially" include in Byzantium and could they potentially take that kind of client load without buckling?

I'm guessing that the Big G's DNSes can take it.  4.2.2[1-4] have been online for years on end, a lot of people use them, and in my experience they're pretty stable.  OpenDNS seems okay but if we decide to "officially endorse" them we should at least get in touch with them and ask their permission.

Anyone else?

**Comment by Sitwon** [comment]
Minor correction. 4.2.2.[1-6] are not Google's DNS servers, they belong to Level 3. Google's servers are 8.8.8.8 and 8.8.4.4.

http://www.tummy.com/Community/Articles/famous-dns-server/
https://developers.google.com/speed/public-dns/

**Comment by virtadpt** [comment]
I think we can configure dhcpcd to use public DNSes.  In the dhcpcd.conf(5) manpage there is a config option that might do what we need:

```
static domain_name_servers=8.8.8.8,4.2.2.1,4.2.2.2
```

If we put that in /etc/dhcpcd.conf, it'll be referenced whenever dhcpcd is used to configure an interface but it'll substitute those DNSes for whatever ones the DHCP server that configures the gateway interface sends it.

**Comment by shanel** [comment]
Would there be any concern that in a hostile environment well-known (like Google's) dns servers might be blocked or that there might be some other sort of foul play going on?

**Comment by virtadpt** [comment]
There is indeed that concern.  Unfortunately, picking public DNSes in a hostile network is something of a game of cat-and-mouse.  We pick Google's "luck eights" for public DNSes, they get blocked because they're popular.  We pick Level 3's "Let's install Solaris" DNSes, they get blocked.  Pretty soon, every popular DNS we pick gets blocked.

It's something that we need to discuss on the mailing list.  Maybe somebody lurking has some insight.

**Comment by Sitwon** [comment]
DNS is a hard technology to make distributed or federated. Without relying
on a web of trust you can't easily do distributed name arbitration. One
system I skimmed uses a system similar to Bitcoin, but I haven't had a
chance to really evaluate their model yet.

Ultimately, I think the long term solution to this will be to migrate away
from using DNS and find other mechanisms to help people find the sites and
services they care about.

**Comment by virtadpt** [comment]
Namecoin is interesting but it is built on top of the Bitcoin protocol, which has a few problems insofar as this problem space is concerned: First, a node has to mine Namecoins before FQDNs can be claimed.  Second, this destroys namecoins, i.e., they become single-use and can't be broken down or exchanged or re-used.  Also, it's not a DNS implementation (it doesn't speak the DNS protocol, so it doesn't do FQDN resolution).

In the long term.

**Comment by Sitwon** [comment]
This is a complicated issue and not one that we can solve for generically. It will have to be up to the end-users to make informed decisions on the ground based on the best intel they have available to them.
