### ISSUE TITLE
We need a website.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#60]
A real website.  I know, we have the wiki pages and Github, but it would also behoove us to set up a real website that has the who, what, where, when, why, and how, official documentation (when we get it put together), necessary PGP keys, links to mirrors, and official downloads of the .iso images and PGP keys.

I own two domains (byzantium-linux.org and project-byzantium.org) and haxwithaxe owns two as well.  My domains are parked at Dreamhost for the time being.  I'd be happy to set up another user account that controls the Project Byzantium website, set up a CMS of some kind, and have someone act as webmaster.

Thoughts?  Suggestions?  This is fairly important seeing as how we're working toward our first release of Byzantium Linux.

**Comment by cshepp** [comment]
I put this website together: http://digicom.lvc.edu/cshepp/byz/index.php

It's just a shell right now, but if you like it I'd be happy to develop it further.

**Comment by virtadpt** [comment]
cshepp, I'd like to introduce you to laurelindel, the other web developer at Byzantium.  laurelindel, this is cshepp.  I think, if the two of you are emanable, that you could put together a kick-ass website for Byzantium.

Also, we have a logo in the Git repository (byzantium-logo.svg) that the two of you should take a look at.

**Comment by cshepp** [comment]
Hi laurelindel. I'm not sure what you've done already, but I'm willing to help with whatever you need. I'm most familiar with html, css, javascript, and php; but I know a smattering of other things. If you want any of the source files for the site I put together or any images or anything, just let me know. I think after the Byzantium website is well on its way (when we have a firm concept of design) it would make sense from a UX perspective to work on making the Control Panel's interface mirror the website's interface. Anyway, just yell if you need my help.

**Comment by cshepp** [comment]
I haven't heard from laurelindel at all. Any news on the website?

**Comment by virtadpt** [comment]
I spoke to him tonight.  He's going to get in touch with you ASAP.

**Comment by laurelindel** [comment]
Hey there. I'm sorry I've been offline; I had an upper respiratory infection and had to jump into getting the February issue of the magazine I work for ready to post on our website. I agree with giving the Control Panel's interface the same look and feel as the website, for sure. I know HTML, CSS, and XML and a very small amount of Javascript, and am teaching myself Python and Unix (slooooowly). I think working together would be great. I can't message you without an email addy, apparently - my email address is laurelindel at gmail dot com. Email me so we can talk directly?

**Comment by virtadpt** [comment]
How goes the website?

**Comment by mtb-za** [comment]
I also e-mailed Laurelindel a while ago to throw my hat into the ring. Not heard anything yet.

cshepp: Maybe we should talk in the meantime? (I would message you, but you have not provided an e-mail address here)

**Comment by laurelindel** [comment]
Hi guys. Unfortunately, I've been hit with work that's kept me from getting anything done on this. To make this happen in a somewhat timely fashion, I'm handing this off to you.

FWIW, I agree that a Wordpress site would probably be the best option, so that people who aren't coders can still contribute to the site. I do have time this weekend to work on the logo, keeping the seeds inside the pomegranate as they are but retooling the outline. I can get the SVG file for that in here by Monday.

**Comment by cshepp** [comment]
Another CMS that I've been using for clients lately is Concrete5. It's much faster to develop than wordpress- make a template in HTML/CSS, insert 5 lines of PHP, and you've got a fully-functional website with an in-context editing system. Either way, first step is some basic information architecture and layout. So....how about this: everyone who's interested in helping out, email me the answers to a few questions (cas002@lvc.edu) :

1) In what area(s) would you like to help out? (IA, Design, HTML/CSS, Back-end, Content, etc)
2) Do you use dropbox, or can you suggest another tool to easily share wireframes, etc?

I'll put together some sort of schedule and let everyone know what's going on. I'm looking forward to making some progress  :)

-Cody

**Comment by virtadpt** [comment]
Right now, whoever gets the site together, gets the site together.  We can host it on Github if we need to.  We've got unlimited space and bandwidth at Dreamhost.  Git'r'done, post a comment on this ticket, and we'll see what happens.

**Comment by hamburgersushi** [comment]
So shepp has that page all pretty much done, and we have hosting.  What are the barriers to getting this live?

**Comment by cshepp** [comment]
I'm making some design, layout, and IA changes (getting rid of that nasty pink, going for a nice, cool "technology blue"). It should be ready within the next few days. I'll post a link.

**Comment by ghost** [comment]
Awesome.  Need any help with any aspects of it?

(This is 'hamburgersushi' - had to consolidate accounts that were lying around)

**Comment by virtadpt** [comment]
Honestly?  The only barrier is pullin gthe trigger and saying "let's do it."

cshepp, please post a link to your new prototype in a comment when it's ready.

We can either host it on Github, or we can host it on Dreamhost (I have an account there) and we can point our domains at it (all four of them).

We still need to decide if we're going to keep using the wiki on hacdc.org or if we're oging to migrate it to Github's wiki.  Personally, I'm leaning toward putting it on Github.

**Comment by ghost** [comment]
I agree.  We might as well just link to the github wiki from hacdc.  It's a separate enough project / large enough to be on its own to that extent.

**Comment by cshepp** [comment]
Ok, here's the rough design/layout/structure.

http://codyshepp.com/byzantium/

A few things:
1) nav at the top will have drop-downs as follows: (please suggest any changes/additions - easier to change now rather than later)
-Home
-About
---the project
---the team
-Documentation
---Wiki
---Getting Started
---How to's
-Community
---Forums
---Mailing List
---Report Bugs
-Dev Resources
---Github
---PGP keys
---???more

The "Resources" section at the bottom right is going to be a (pretty) list of all external sites and some more important internal ones. Please suggest anything you think is missing here. They'll all need at least a little blurb explaining what it is and what you can do there (anyone is more than welcome to write those).

The 'interior' pages will be similar, but the white section will begin just under the logo/nav (no download/graphic section).

Finally, if anyone is interested in replacing the greek text on this first page, just shoot me an email with the copy (cas002@lvc.edu). 

Let me know your thoughts.

**Comment by virtadpt** [comment]
Downloads: Links to the latest torrents and mirrors online.

I don't think we have enough users to warrant setting up forums yet.  Let's wait until our first beta release.

The mailing list should probably go under the developers' resources.  So should a link to the bugtracker.

**Comment by virtadpt** [comment]
project-byzantium.org has been set up at Dreamhost; cshepp has been sent login credentials to the server.  byzantium-linux.org redirects to project-byzantium.org.  haxwithaxe was asked to point his two registered domains at project-byzantium.org on IRC this afternoon (I forgot to ask yesterday).

**Comment by virtadpt** [comment]
project-byzantium.org looks good - we've got some content, it just needs to be fleshed out with stuff from the HacDC wiki page and the FAQ.

**Comment by virtadpt** [comment]
Bennett Kobb noticed something about the website - the text in the blocks on the frontpage is stuck underneath the buttons.  I looked at it on Windbringer (Firefox v9.0.1, Arch Linux) and it's fine.  Looking at it from inside of Byzantium (also Firefox v9.0.1), it's messed up.

I don't know what's going on there but I thought I'd add it to the ticket.

**Comment by virtadpt** [comment]
The website has been migrated by Seele to Wordpress.  It has been tested and is now running at http://project-byzantium.org/.
