### ISSUE TITLE
Disable automounting of node's hard drives, spin down hard drives to extend battery life.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#66]
When Porteus Linux boots up, one of the first things it does is probe for and automatically mount any and all hard drives of the machine it's running in to make them available to the live OS.  This is potentially problematic for several reasons.

First, by spinning up the local hard drives if they're not being used, more power is being used by the system.  For portable systems (like laptops) not connected to mains power this uses up their batteries faster, resulting in shorter runtime before recharge.  Perhaps it would be a good idea to investigate how Porteus Linux implements this and turn it off by default.  We'll probably have to check a few of their initscripts into Git so we can edit and maintain forks of them to implement this.

Second, in the event a node is compromised the internal hard drives will be exposed to the attacker.  This could result in data corruption, or a terminal loss of the node admin's anonymity if the attacker is part of the threat model of a Egypt Problem-like scenario and decides to go through the documents on the drives.

**Comment by Sitwon** [comment]
I'm hesitant to do this because I developed almost the identical feature for a commercial bootable Linux project and they were trying to patent the work I had done for them. As much as I don't like software patents, I don't want to be a jerk to those guys and look like I'm undermining their product.

**Comment by virtadpt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 12/10/2011 08:42 AM, Ben Mendis wrote:

> I'm hesitant to do this because I developed almost the identical 
> feature for a commercial bootable Linux project and they were
> trying to patent the work I had done for them. As much as I don't
> like

They were trying to patent hard drive spin-down?  That's bullshit.  To
say nothing of the fact that somebody probably already owns a patent
on it.

> software patents, I don't want to be a jerk to those guys and look 
> like I'm undermining their product.

This is an opensource project - if somebody just happens to publish an
.xzm module which implements this functionality, we can't stop them.

---

The Doctor [412/724/301/703]

PGP: 0x807B17C1 / 7960 1CDC 85C9 0B63 8D9F  DD89 3BD8 FF2B 807B 17C1
WWW: https://drwho.virtadpt.net/

If it's not on fire, it's a software problem.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iEYEARECAAYFAk7knsAACgkQO9j/K4B7F8GQkQCfWSzLG1R5Ru5zNJY7iiX0eNzM
5kQAoMPP5ZXrAyS/Mn4DGbnoMmmL4SVU
=Xnot
-----END PGP SIGNATURE-----

**Comment by Sitwon** [comment]
They patent wasn't for hard drive spin-down but for not mounting the hard drives and making them inaccessible during the boot up. I don't know exactly what they wrote in the patent application but I could probably look it up.

Also, I'm not saying that it shouldn't be included in Byzantium, just that I probably shouldn't be the one to work on that particular aspect so that they can't claim I was violating a non-compete or something.

**Comment by virtadpt** [comment]
Could you dig up that patent application so we could take a look at it?  There's a lot of prior art behind this (going all the way back to Knoppix v1.0) so I think we'd be safe.  Still, if you'd prefer to not work on it for professional reasons another of us could, and we could track ownership of the work in the Git repository.

We could hardcode the not mounting drives bit by adding the 'noauto' and 'noswap' cheatcodes to the xconf and lxde stanzas in boot/porteus.cfg.  We could also call an initscript from etc/rc.d/rc.local to see if 'noauto' is present in /proc/cmdline and if so walk through /\/dev\/[hs]d?/ and run hdparm on them to power them down with the -Y option (immediately enter standby mode - http://linux.die.net/man/8/hdparm).

This might also be helpful: http://blog.mymediasystem.net/uncategorized/simple-way-to-spindown-a-sata-hard-disk-drive-after-being-idle-linux/

**Comment by SpartacusAU** [comment]
Not mounting the hard drives seems quite obvious as a security precaution. I was surprised to see they were mounted when I was running from RAM. My friend noted they were mounted and he was also concerned. 
The drives can be mounted after start up from the OS itself, so I agree unmounted start is good for security and battery life considerations, but security is the bigger consideration.

Back in the day I had a ZX81 (aka Timex 1000) in 1981 ( which of course was patented) it didn't mount drives on start up so I think trying to get/enforce a patent on that feature might be hard to do.

The patent war over the 386 is strangely relevant.

Logic would dictate that if i am not going to use a hard drive to boot there is no need to mount hard drives on boot.
perhaps not even search for drives on boot either.

I realize this is an old thread but I saw my drives mounted yesterday so I need to push this.

I know very little about Linux, have used Byzantium v02a for only a few day and I can see the need for this.
Agree that Sitwon should not code it though.

I do know a bit about security though, hat tip to all the people employed to read this....

Patents... maybe I should patent the letter e, the note c, one of the 4 DNA base pairs, or the idea of open source software and really screw everyone.

**Comment by virtadpt** [comment]
It should be fairly simple to disable the automounting of hard drives at boot time.

Doing a bit of background reading, Porteus Linux is not supposed to automount drives on boot (http://forums.fedoraforum.org/archive/index.php/t-279163.html).

Going through our code repo, the file Byzantium/scripts/11-media-by-label-auto-mount.rules (https://github.com/Byzantium/Byzantium/blob/master/scripts/11-media-by-label-auto-mount.rules) appears to do the work of automounting drives.  By omitting this file from the build, it should prevent hard drives from being automatically mounted.

**Comment by SpartacusAU** [comment]
If you make this change, will it be possible to mount the drives after boot has completed or not?
Would be nice to have this option.

Is it worth having an option on boot to make drives not possible to mount?

Extra security measure - never mount drives?

**Comment by virtadpt** [comment]
It will still be possible to mount drives after the node boots up, but it will have to be done manually (from the shell) or from the desktop environment. This only disables automount.

Here's the thing about automounting: By doing so it exposes the contents of whatever storage media you have on your machine, which can potentially expose identifying information through your node.  By giving the user a choice to do so they are less likely to accidently out themselves.

Also, this: dc32372e3ddc92129865c040f8789d01dd98033d

**Comment by SpartacusAU** [comment]
Agree about risks of auto mounting.
Would it be possible to have a warning message when attempting to mount drives form shell or the desktop environment?

Something like this:

"Mounting a drive potentially exposes the contents of the storage media to an attacker."
"Are you sure you want to Mount drive?" 
"Mount Drive"         "Disconnect from mesh and networks then mount drive"      "Cancel"

And I'm not sure if this is going to help much but better than nothing I guess.
 "Disconnect from mesh and networks then mount drive"

**Comment by virtadpt** [comment]
It might be safer to not draw attention to it at all.  Linux users who're used to mounting drives are going to do it regardless of warnings - by definition, they know what they're doing.  Unskilled users aren't going to know what it means, and as such probably shouldn't be given that risk.

**Comment by virtadpt** [comment]
We can test this by not putting Psypete's udev rule file into a distro and trying it.  That should disable automounting at boot-time while still leaving it possible to mount them manually (say, with the file manager).

**Comment by haxwithaxe** [comment]
status?

**Comment by virtadpt** [comment]
The Porteus Linux docs (http://www.porteus.org/component/content/article/26-tutorials/general-info-tutorials/117-cheatcodes-what-they-are-and-how-to-use-them.html) say that the 'noauto' cheatcode can be used to prevent automounting of drives.

Fixed in commit b1c156e77a1a061af15b83cda9b0f9122b626907.
