### ISSUE TITLE
Change the graphics displayed by the environment.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#69]
The Porteus image we're using for Byzantium v0.1a still has Porteus Linux graphics for the boot loader, desktop, and login screen.  We should really develop graphics that are Byzantium-specific to give a more consistent user interface.

**Comment by virtadpt** [comment]
I rewrote the cosmetic bits of the boot loader's config files and hacked together a crappy splash screen for the .iso image.  We still need one that doesn't suck, and we could also use backgrounds for KDE and LXDE that are Byzantium-specific.  I can patch such a thing together but I'm no graphical designer.  I could, however, insert the graphics into the relevant .xzm files to make them the defaults.

**Comment by virtadpt** [comment]
The boot/porteus.cfg file should be fixed up so that the text is more accurately positioned on the screen.  It should be in the syslinux documentation (http://www.syslinux.org/wiki/index.php/The_Syslinux_Project) someplace, we'll just have to go digging around in there.

Specifically, we need to push everything down about three rows.

**Comment by virtadpt** [comment]
The following link will be useful for changing the appearance of KDE v3.5:

https://www.linuxquestions.org/questions/linux-software-2/how-do-you-change-the-splash-screen-246165/#post1254312

It also should be possible to use the KDE Look-and-feel editor to change the background, figure out what changed in /home/guest/.config, add it to the Git repo, and then copy it into /tmp/fakeroot/home/guest.

**Comment by virtadpt** [comment]
LXDM themes should be found under /usr/share/lxdm/themes/<theme name>

**Comment by virtadpt** [comment]
When you use the KDE "change the background" feature, it doesn't change anything in /home/guest.

The desktop backgrounds are kept in /usr/share/wallpapers.

I hacked this together and put it into my VM: flickr-ms_midnight_maniac-spideweb-1-1.jpg

I now need to figure out how to make it the default background on login.

**Comment by virtadpt** [comment]
This might help with creating LXDM themes: http://wiki.lxde.org/en/Desktop_Design

**Comment by virtadpt** [comment]
This can be used to build OpenBox themes, which are for the LXDE desktop side of the distro.

**Comment by Sitwon** [comment]
Haxwithaxe has fixed this stuff.
