### ISSUE TITLE
Clean up and re-organize the Git repository.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#71]
We have scripts and configuration files all over the Git repo.  They really need to be organized into a structure that makes sense, rather than the ad-hoc one we've been using.  When this is done, the build process in the wiki needs to be updated along with it.

We should do this as a group so that we don't step on each other.

**Comment by virtadpt** [comment]
Do we really need to keep the following around:

ahcpd/
batman-full/batman/ (BATMAN is deprecated; BATMAN-adv replaced it)
config_files/ahcpd/
config_files/dhcpd/
config_files/dns/
porteus/sqlitebrowser/ (I keep that around for development, it's not used by the live OS)
porteus/wifidog/
sweetspot/
wifidog-auth-lite/

We might want to keep the following around for future compatibility:
batman-full/

**Comment by virtadpt** [comment]
There is a directory Byzantium/scripts/ which contains scripts used by the underlying Porteus OS for various things.  This is good.

There is a directory Byzantium/porteus/ which contains directories for packages build for Porteus Linux that we need.  Some of them contain entire Slackbuilds, others just config files.  This is kind of sloppy and confusing.  It also complicates the construction of 000-byzantium.xzm.  We should do something about this.

Why don't we create Byzantium/config_files/ to hold the custom configuration files we have under revision control (like etc/[passwd,shadow,sudoers])?

This is something we should really sit down and whiteboard because it's a big job, and easy to screw up.

**Comment by virtadpt** [comment]
Deleted a bunch of stuff sitting around that we don't need anymore (like the other captive portal implementations and binaries that don't need to be in there).

Relevant commits: f2ece9ddb4, b218e46ea8, 8e856d65e2.

**Comment by haxwithaxe** [comment]
we really should segment the byzantium specific code from the sysadminy stuff. and make the M and C bits of the python into packaged modules and i'm not sure about the V stuff but that might be something to stick into a packaged module as well.
at some point we should also think about spliting the repo into seperate repos for the seperate parts of the system but that might not be something people will accept due to the eek-factor of subrepos.

**Comment by virtadpt** [comment]
Deleted a bunch of stuff that never worked and old SlackBuilds.

We really should look into making a skeleton fakeroot directory with all the stuff that doesn't go into packages in it to speed up the fakeroot creation process.  That'll also give us a chance to clean a lot of crap out.

**Comment by haxwithaxe** [comment]
done
