### ISSUE TITLE
Enable Avahi/Zeroconf support for Byzantium Linux.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#77]
Avahi/Zeroconf is a protocol which allows arbitrary nodes that have no foreknowledge of one another to find and interact with one another on a network.  It was originally designed to make it easy to locate printers, media machines, and other services but can be extended to cover arbitary services (such as SSH or IRC).

We need to work up a set of Avahi configuration files to announce the presence of various services running on the nodes that comprise a Byzantium mesh, i.e., IRC, WWW, Etherpad-Lite, FTP, et al.

**Comment by virtadpt** [comment]
ngIRCd (the IRC server) natively supports Zeroconf.  We just have to configure it properly.

**Comment by virtadpt** [comment]
I tried to paste a sample avahi .service file in this comment but I'm having trouble pasting the XML into this comment field.  I'll try again later.  Suffice it to say that writing a service descriptor is easy.  The descriptors can be kept in the directory /etc/ahavi/descriptors and copied into /etc/avahi/services by the control panel, followed by `avahi-daemon -r` to reload the list of services it knows about.

avahi-daemon then begins to broadcast the services running on that node to the rest of the mesh... the question is, how to get what a node's avahi daemon is aware of onto the node's frontpage where it can be browsed by mesh clients.

**Comment by virtadpt** [comment]
We should package the .service files when we run the SlackBuilds.

`avahi-daemon -r` can be run by the 'start' stanza of the initscripts when they're executed.  Come to think of it, they can copy the .service files into the avahi-daemon's service descriptor directory and delete them when the 'stop' stanza is executed.  The originals can be kept in a static archive directory under /etc/avahi.

**Comment by virtadpt** [comment]
Added nss-mdns package.  I'm now getting this error message from avahi-daemon (run manually with the --debug switch for debugging):

`Failed to add DNS server address: Not supported`

Reference commit: c619d75a89fd287d2a530c1dba68071aea929011

**Comment by Sitwon** [comment]
Finally working!
