### ISSUE TITLE
We need a QA process!

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#78]
As you've no doubt heard, when v0.1a was shipped we forgot the 000-byzantium.xzm file containing all of the Byzantium-specific systemware.  This means that we shipped without anything we did, just a null respin of Porteus.

This.  Cannot.  Happen.  Again.

Yes, I screwed up.  Badly.  I remastered the .iso image, so the ball was in my court, and I've got a double helping of crow on my plate tonight.

However, when I ask (sometimes beg) people to check my work (especially before a release), there's a good reason for it - to keep things like this from happening.

Therefore, I propose that prior to ANY release of any kind, at least one other person actually tests or looks over (depending on what the release is) the product to make sure that it has what it's supposed to and will do what we want it to.  We can't have this happen ever again.

**Comment by haxwithaxe** [comment]
in addition to us (where name!=virtadpt) not being preoccupied and lazy a set of simple scripts to check that things are where they need to be before building might not be a bad idea. a line with "if [ ! -e $file ];then echo $file is missing ; exit 1 ;fi" or a for loop over a manifest might be a good idea at several stages. i'm guilty of similar oversights on occasion as well ("hmm that directory was there when i tested ..." he says while on the production server). we've done the right thing so far and it's only an alpha release so the damage (if any) is minimal.
edit: also we might want to build the isos test for a couple days (without rebuilding unless some horrible system breaking flaw is found) then release ... clearer heads tend to prevail more easily when they have time to sleep and recaffeinate :P

**Comment by laurelindel** [comment]
Give me a list of what needs to be on any given release and I can QA to make sure it's actually there before we hit go. I'm willing to do this as a matter of course, going forward.

**Comment by haxwithaxe** [comment]
have a look. this is only a draft.
http://wiki.hacdc.org/index.php/Byzantium_Live_Distro_Prerelease

**Comment by virtadpt** [comment]
I've added some things to the QA process on the wiki.

**Comment by jjerrodtaylor** [comment]
Do you all have any automated unit tests, functional test, etc... for anything. I was looking through your code base and I couldn't find any.

**Comment by virtadpt** [comment]
We need automated unit tests but don't have any yet.  Our functional testing is manual and, frankly, needs to be formalized and documented.  We need help with that.

**Comment by jjerrodtaylor** [comment]
Then this is something that I'll just start on.

**Comment by virtadpt** [comment]
Automated unit tests are being constructed for the control panel at this time.

**Comment by Sitwon** [comment]
Refer to the wiki: https://github.com/Byzantium/Byzantium/wiki/Release-Procedures
