### ISSUE TITLE
byzantium-v0.1a install to USB ext3 *errors* via lin_start_here.sh

### ISSUE THREAD

**Issue by guinness1** [Byzantium/Byzantium#79]
hi all, 

the following paste shows the results from using the lin_start_here.sh script (from /boot on usb key - copied files) and selecting option 6 -> for same usb key formated using gparted as ext3 and boot flag enabled. I mounted  the iso as loop device, then 'rsync -rv /mnt/loop/\* .'  to copy all files to usb key --> all done as root. I added a portion of 'uname -a' for completion.  ubuntu 11.11 I believe. 

cheers,

gs1

---

root@cheerzzz:/media/Byz/boot# uname -a
Linux cheerzzz 2.6.38-13-generic #53-Ubuntu SMP  i686 i686 i386 GNU/Linux

root@cheerzzz:/media/Byz/boot# ./lin_start_here.sh 

```
          _.====.._
        ,:._       ~-_
            '\        ~-_
              \        \.
            ,/           ~-_
   -..__..-''   PORTEUS   ~~--..__
```

--==--==--==--==--==--==--==--==--==--==--==--==
            Welcome to Porteus-v1.0  
--==--==--==--==--==--==--==--==--==--==--==--==

[1] Check for Porteus update
[2] Read Porteus requirements
[3] Read Porteus installation instructions
[4] Read Porteus cheatcodes
[5] Read about bootloaders
[6] Install Porteus to EXTx partition (extlinux)
[7] Install Porteus to FATx partition (syslinux)
[8] Install Porteus to any partition (lilo)
    no graphical - only text menu available
[9] Quit this application

Please choose a menu item ...
6

/media/Byz/porteus /media/Byz/boot

-e \e[36mChecking md5sums - wait a while...

[: 41: 2fc88f67f4d67999fee2a929c4bd3f0f: unexpected operator
-e checking md5sum for  ../boot/vmlinuz   \e[31mfail!
[: 41: eef4c7d9e410d4099171ac083eda0cef: unexpected operator
-e checking md5sum for  ../boot/initrd.xz   \e[31mfail!
[: 41: bb530ef1b0d9f714ba3ba707525690d1: unexpected operator
-e checking md5sum for  ./base/000-kernel.xzm   \e[31mfail!
[: 41: daf2b3afdb61e305b1fd3f62a2682e13: unexpected operator
-e checking md5sum for  ./base/001-core.xzm   \e[31mfail!
[: 41: bd15c3b7aebb3f1e5a490d49296d312b: unexpected operator
-e checking md5sum for  ./base/002-xorg.xzm   \e[31mfail!
[: 41: 494ac56997d995eb0be1af3bb4bee858: unexpected operator
-e checking md5sum for  ./base/003-lxde.xzm   \e[31mfail!
[: 41: be6268a95287a4e9aa0b62eceec22289: unexpected operator
-e checking md5sum for  ./base/004-kde.xzm   \e[31mfail!
[: 41: c47dcad4fdc2df7c9ba16d6acd51ebd0: unexpected operator
-e checking md5sum for  ./base/005-kdeapps.xzm   \e[31mfail!
[: 41: 8950543bff042c6d4cc48b1ea80bb1e4: unexpected operator
-e checking md5sum for  ./base/006-koffice.xzm   \e[31mfail!
[: 41: 56f555d51b13ea46877745bd07297261: unexpected operator
-e checking md5sum for  ./base/007-devel.xzm   \e[31mfail!
[: 41: 52e4f1541450eaf9312a43345110b628: unexpected operator
-e checking md5sum for  ./base/008-firefox.xzm   \e[31mfail!

-e \e[31mSome md5sums doesn't match or some files from default ISO are missing,
please check above...
-e \e[31mBe aware that vmlinuz, initrd.xz, 000-kernel.xzm and 001-core.xzm
are most important and booting wont be possible when they are missing.
-e \e[36mPress enter to continue or ctrl+c to exit
read: 54: arg count
root@cheerzzz:/media/Byz/boot#

---

**Comment by haxwithaxe** [comment]
oddly enough i get the same error when my root partition is full (as in free space = 0.0B ... don't ask :P) but after i make some space the error goes away. is your root partition full by any chance? if not can you run md5sum on the files that are being reported as failing the check? the xzm's listed should be in "porteus/base/".

**Comment by guinness1** [comment]
---

space on root partition looks good:

df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu-root  25G   12G   12G  52% /

---

md5sums are the same as in the errors.  the error indicates "unexpected operator -e" while checking the md5sums, and |e[31fail!  <-- nice msg... at least it wasn't epicfail !  ;)

md5sums:

md5sum ./*.xzm
bb530ef1b0d9f714ba3ba707525690d1  ./000-kernel.xzm
daf2b3afdb61e305b1fd3f62a2682e13  ./001-core.xzm
bd15c3b7aebb3f1e5a490d49296d312b  ./002-xorg.xzm
494ac56997d995eb0be1af3bb4bee858  ./003-lxde.xzm
be6268a95287a4e9aa0b62eceec22289  ./004-kde.xzm
c47dcad4fdc2df7c9ba16d6acd51ebd0  ./005-kdeapps.xzm
8950543bff042c6d4cc48b1ea80bb1e4  ./006-koffice.xzm
56f555d51b13ea46877745bd07297261  ./007-devel.xzm
52e4f1541450eaf9312a43345110b628  ./008-firefox.xzm

md5sum vmlinuz 
2fc88f67f4d67999fee2a929c4bd3f0f  vmlinuz

md5sum initrd.xz 
eef4c7d9e410d4099171ac083eda0cef  initrd.xz

---

**Comment by haxwithaxe** [comment]
i keep getting roughly the same thing when building straight proteus except when i was logged on as root (not su'd or sudo'd). give it a try when logged on as root. idk if it had anything to do with it but i was in a textmode only when it worked flawlessly as well. also can you post the copy of the lin_start_here.sh you're using? i've been staring at mine for a couple hours on and off and not seeing where there is an error (despite it being clear where the script is failing/stuttering).
if you just push through the script do you get a bootable usb? it doesn't seem to matter when i just "press enter to continue" the porteus and byzantium builds i've done for myself seem to work fine regardless.

**Comment by guinness1** [comment]
ok, i managed to fix the problem.  I now have a working/booting Byzantium USB key (formatted ext3).

The issue(s) were in '/porteus/chkbase.sh' file.
Note: chkbase.sh works fine _as is_ when it is run on its own (not called from another script).

it seems that chkbase.sh when called form another script has a problem with the operator '==' in an 'if' test. it also has issues with the '-eq' operator when called from another script.  it works fine using the single '=' when called from another script. so, i changed:

```
if [ "$first" == "$second" ];then
```

it works when the operator is:

```
if [ "$first" = "$second" ];then
```

also, the script exits instead of returning to parent script and continuing with the installation.  this can be seen in the original post (paste of output) --> "read: 54: arg count"

the last line of file chkbase.sh has only a 'read' statement. explicitly adding a variable/name solved the problem.  the 'read' seems to need a container to hold text (or no text) and continues when it receives a carriage return - at least that is what a little googling told me. so this cleared the "read: 54: arg count" error.

was:  read

changed to:  read junk

Note for haxwithaxe:  observations and answers to your questions:  I was using 'root' from the start, not su or sudo.  I was not able push through with the install as the 'read' issue prevented it (it did got through when I commented out the md5sum section). btw. im not sure what you mean by being in textmode, but this prompted me to read the script and find all the scripts to test individually and within parent scripts (cheers).  the chkbase.sh script defines 'out=/tmp/md5sums.txt$$' - since it uses /tmp , maybe having no space left in the root partion would affect the file being written and causing errors similar/exactly like the errors i experienced.  although the problem was not with 'lin_start_here.sh', would you still like to see it here for extra info, or anything else that could be helpful?
Thank you for helping out with this problem - cheers :)

gs1

---------------- original chkbase.sh ----------------

#!/bin/bash

# script by fanthom

# Variables

md5=`which md5sum`
out=/tmp/md5sums.txt$$
c='\e[36m'
r='\e[31m'
e=`tput sgr0`

# Let's start

if [ "$md5" = "" ]; then
    echo -e "${r}md5sum utility is missing - can't perform md5sum check, exiting..."$e | fmt -w 80
    exit
fi

echo && echo -e "${c}Checking md5sums - wait a while..."$e
for x in `find ../boot/initrd.xz` `find ../boot/vmlinuz`; do
    md5sum $x >> $out
done

for x in `find ./base/* | sort`; do
    if [ ! -d $x ]; then
        md5sum $x >> $out
    fi
done

echo
num=`grep -c / md5sums.txt`; x=1
while [ $x -le $num ]; do
    file=`awk NR==$x md5sums.txt |  cut -d " " -f2-`
    first=`awk NR==$x md5sums.txt |  cut -d " " -f1`
    second=`grep $file $out |  cut -d " " -f1`
    if [ "$first" == "$second" ];then
    echo -e "checking md5sum for $file    ${c}ok"$e
    else
    echo -e "checking md5sum for $file   ${r}fail!"$e
    fail="yes"
    fi
    x=$(($x+1))
done
rm $out

echo
if [ "$fail" ]; then
echo -e "${r}Some md5sums doesn't match or some files from default ISO are missing, please check above..."$e | fmt -w 80
echo -e "${r}Be aware that vmlinuz, initrd.xz, 000-kernel.xzm and 001-core.xzm are most important and booting wont be possible when they are missing."$e | fmt -w 80

else
    echo -e "${c}All md5sums are ok, you should have no problems with booting Porteus!"$e | fmt -w 80
fi

echo -e "${c}Press enter to continue or ctrl+c to exit"$e
read

---

---------------- modified chkbase.sh ----------------
#!/bin/bash

# script by fanthom

# Variables

md5=`which md5sum`
out=/tmp/md5sums.txt$$
c='\e[36m'
r='\e[31m'
e=`tput sgr0`

# Let's start

if [ "$md5" = "" ]; then
    echo -e "${r}md5sum utility is missing - can't perform md5sum check, exiting..."$e | fmt -w 80
    exit
fi

echo && echo -e "${c}Checking md5sums - wait a while..."$e
for x in `find ../boot/initrd.xz` `find ../boot/vmlinuz`; do
    md5sum $x >> $out
done

for x in `find ./base/* | sort`; do
    if [ ! -d $x ]; then
        md5sum $x >> $out
    fi
done

echo
num=`grep -c / md5sums.txt`; x=1
while [ $x -le $num ]; do
    file=`awk NR==$x md5sums.txt |  cut -d " " -f2-`
    first=`awk NR==$x md5sums.txt |  cut -d " " -f1`
    second=`grep $file $out |  cut -d " " -f1`

```
if [ "$first" = "$second" ];then      ###################
echo -e "checking md5sum for $file    ${c}ok"$e
else
echo -e "checking md5sum for $file   ${r}fail!"$e
fail="yes"
fi
x=$(($x+1))
```

done
rm $out

echo
if [ "$fail" ]; then
echo -e "${r}Some md5sums doesn't match or some files from default ISO are missing, please check above..."$e | fmt -w 80
echo -e "${r}Be aware that vmlinuz, initrd.xz, 000-kernel.xzm and 001-core.xzm are most important and booting wont be possible when they are missing."$e | fmt -w 80

else
    echo -e "${c}All md5sums are ok, you should have no problems with booting Porteus!"$e | fmt -w 80
fi

echo -e "${c}Press enter to continue or ctrl+c to exit"$e

read junk    #########################

---

**Comment by virtadpt** [comment]
guiness1, I've noticed the same thing when just trying to install plain-jane Porteus v1.0 on USB keys and virtual machines.

Nice work on the script - could you fork the Byzantium repo on your end (http://help.github.com/fork-a-repo/), do a `git add` to the script under Byzantium/porteus/ in your fork, and push it?  We'll take a look at it, compare it to the script in Porteus v1.1 (https://porteus.org/forum/viewtopic.php?f=44&t=747), and merge it into the mainline Byzantium repo.

**Comment by guinness1** [comment]
I'm having problems forkin cloning... (noob doing this)

it's a minor change.  maybe someone could add it in an existing fork?

cheers

gs1

---

Cloning into Byzantium...
The authenticity of host 'github.com (207.97.227.239)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,207.97.227.239' (RSA) to the list of known hosts.
Permission denied (publickey).

## fatal: The remote end hung up unexpectedly

**Comment by virtadpt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 01/22/2012 01:05 PM, GuinnessSmoothie wrote:

> I'm having problems forkin cloning... (noob doing this)

Have you seen this?

http://help.github.com/fork-a-repo/

> it's a minor change.  maybe someone could add it in an existing
> fork?

Sure.  Attach the script to a post on the mailing list and we'll take
a look at it.

> ---
> 
> Cloning into Byzantium...
> The authenticity of host 'github.com (207.97.227.239)' can't be
> established. RSA key fingerprint is
> 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48. Are you sure you
> want to continue connecting (yes/no)? yes Warning: Permanently
> added 'github.com,207.97.227.239' (RSA) to the list of known
> hosts. Permission denied (publickey). fatal: The remote end hung up
> 
> ## unexpectedly 

Hmmm...

> are you cloning from the HTTPS URL or the Git URL?  Try the
> read-only one and see if it works:

git://github.com/Byzantium/Byzantium.git

This might be a configuration issue that we should solve and document,
just in case.

---

The Doctor [412/724/301/703]

PGP: 0x807B17C1 / 7960 1CDC 85C9 0B63 8D9F  DD89 3BD8 FF2B 807B 17C1
WWW: https://drwho.virtadpt.net/

Lawful Evil: Doing the right thing for all the wrong reasons.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iEYEARECAAYFAk8cf+8ACgkQO9j/K4B7F8GuPwCcD1al3HXPRBs6FSaBIoauuH2S
nasAn2nBHvJGr4DeyCWJ9LbnJYqMjYsl
=dAh/
-----END PGP SIGNATURE-----

**Comment by guinness1** [comment]
I was setting up a local repo as detailed in http://help.github.com/fork-a-repo/

git://github.com/guinness1/Byzantium.git <-- this is working for me, I have a local copy now.

good call on noting the HTTPS.  I was actually using the SSH link, as it looked like what was described in the fork-a-repo help link.  trial and error and a little help. thank you virtadpt

trying to work out how/where to make the change and push it to my fork.  still a little confusing atm..

cheers,

gs1

**Comment by guinness1** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

not sure where the script is located in the clone image, or how to 'git
add' it. hmmm..

any help appreciated. thanx

gs1

**Comment by virtadpt** [comment]
Ok, take that copy of chkbase.sh you modified to fix the bugs and copy it into Byzantium/scripts/.  Do a `git add chkbase.sh` to put it under revision control in your personal repository and then do a `git push` to upload the changes made to your fork to Github.  Then hit the "Switch branches" widget on the Github page for Byzantium, switch to your personal fork, then click the "Pull request" widget at the top.  Enter a title for the pull request and a description of what you did (referencing this ticket would help us keep everything straight)...

It would be easier to just reference the page I'm cribbing from: http://help.github.com/send-pull-requests/

**Comment by guinness1** [comment]
virtadpt,

thank you for the file location information and link for pull requests.

I managed to git add file. git push fails and suggests using the ssh link (that does not work due to pubkey). 

it looks like I will have to read up on all this github repo stuff and sort it out at some point. certainly more time consuming then fixing the problem/bug  :p

who knew opening a trouble ticket would lead to this forking conclusion... lol

anyway, if I dont 'join' the forking party anytime soon, the fix details are in the thread.  I hope that small contribution helps for now.

I am more interested in testing Byzantium and seeing if/how I will incorporate Babel mesh in one of my openwrt firmware versions.  github repo details and forks are not really a priority atm. 

keep up the good work. will let you know if I find anything else along the way.

cheers,

gs1

**Comment by Sitwon** [comment]
the == operator within a [ test should function identically to the = operator in Bash. My guess is that the system experiencing the issue wasn't using _real_ Bash but some other Bourne shell clone (probably Dash).

In any case, I've applied the changes and added it to the Byzantium repo. It needs to be copied into the ISO tree we use to master release ISOs so that it will be in the next release, but I'm going to go ahead and close this one for now.
