### ISSUE TITLE
Expire inactive MACs from the IP tables whitelist.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#86]
Due to the nature of mobile IP clients can stop associating with one mesh node and associate with another more or less at will.  This unfortunately means that IP tables rules for MAC addresses that are no longer within range can potentially pile up and exhaust kernel memory.  A cronjob should run every ten minutes or so (the same length of DHCP leases) a figure out which MACs have been inactive for longer than ten minutes and delete their rules.

captive-portal.sh already has the capability to delete single clients from the set of IP tables rules running on a particular node, so we just have to write the logic to determine which rules to delete.

**Comment by virtadpt** [comment]
One of the captive portal applications we were experimenting with had this capability.  I forget which one (Captive-Portal?)  We can figure out which one it was and replicate that functionality.

I hope it doesn't require ipset...

**Comment by virtadpt** [comment]
It's Captive-Portal (http://search.cpan.org/~gaissmai/Captive-Portal/), and the name of the script that is run by cron is capo-ctl.pl.  We can look at how they did it there and replicate it in our code.

**Comment by virtadpt** [comment]
We should consider using the ipset modules and utility (http://ipset.netfilter.org/) to implement this functionality most effectively.  It's designed for this sort of thing, anyway, and building new kernel modules isn't terribly difficult.  ipset holds client information in key:value format, which for us would be "IP address":"MAC address".

Reading through the code, Captive-Portal maintains a disk cache that is used to keep track of the last time a client was seen.  Reading through the code is going to take a while but the algorithm should be relatively simple.

**Comment by haxwithaxe** [comment]
we would want "ip:mac:lastcount:changetime" so that when the packet count is the same for too long it will expire

my idea goes as follows:
read packet counts -> read cache (where ever it may be) -> for client in packet count do if count > lastcount; update changetime; else if age > max age ; dump client from iptables and cache

we can replace the packet count for any metric we want but the ide is the same either way. we can also store the cache in ram by having a service that runs by itself and only write the cache to disk for backups if it dies unexpexctedly, or not at all if we don't want to write to disk for whatever reason.

i will write the metric independent stuff asap and we can figure out what is needed for determining the clients are dead or alive later if needed.

**Comment by haxwithaxe** [comment]
just added captive_portal/mop_up_dead_clients.py which needs a way to tell if a client is active or not but it will keep track of it and call a function which will remove the clients depending on which method we choose.

**Comment by virtadpt** [comment]
captive-portal.sh has a stanza called 'remove' that, when passed a client's IP address as an additional argument, will delete the corresponding rule for that IP's MAC address.

**Comment by virtadpt** [comment]
haxwithaxe's commit is eca5f456ea68da1167009c1d6b8828b340a7b201.

**Comment by haxwithaxe** [comment]
just want to update that the mop up script is working as intended.
@virtadpt you can call (as a module) it where you want it and as often as you want it. it runs via the mop_up() method and you can put it in a while loop like i have in the included main function.

**Comment by virtadpt** [comment]
Reformatted the code to be more like the rest of our code in ec5cca03967e161b0178ff351c79d7e1a04f1e35.

Fixing a bug in how iptables is being called in 6169fdbcd33c05701bc2a6070eb74ddf697940c8.

Testing in a VM now.

**Comment by virtadpt** [comment]
Integrated into 000-byzantium.xzm fakeroot.

**Comment by virtadpt** [comment]
Working in commit b872489490fdda9f3f8dde07cb64815e80a285c6.
