### ISSUE TITLE
We need a quickstart guide.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#90]
A criticism registered about Byzantium Linux v0.1a was the lack of a quickstart guide in an obvious place.  We have a start at one, in the form of README.txt in the root directory of the .iso image, but it's not in an obvious place.

What I'm thinking is a folder on the desktop named GET STARTED or something (again, with an i18n'd name in the .desktop file) and copies of README.txt (ideally, translated into the appropriate languages).  README.txt already contains the step-by-step process for configuring a node.

I guess what I'm trying to say is that we need to make things a little more obvious.

Comments?

**Comment by virtadpt** [comment]
Since this ticket was opened, some documentation has been written and placed in the root directory of the ISO image (vis a vis, README.txt, README.NOW, FAQ.txt, RELEASE_NOTES.txt, "USB INSTALLATION.txt").  However, not a lot of people are finding it.  From talking to users, they're expecting it to be somewhere on the desktop or in the web browser (sort of like what Windows does with its universal help utility).

I'm thinking that we should make documentation pertaining to booting the image and making boot media available in the root of the ISO image, and documentation on how to actually use Byzantium available on the desktop (like a hierarchy of HTML pages that are opened with the web browser whenever someone clicks on an icon).

**Comment by virtadpt** [comment]
This needs to be put in an obvious place, i.e., on the desktop because not many people went poking around in the root directory of the .iso image.

**Comment by Sitwon** [comment]
Documentation has been written, we still need to stick it in an obvious place.
https://github.com/Byzantium/Byzantium/wiki/Configuring-your-mesh-node

**Comment by starbits** [comment]
I think the first place that needs documentation is the CD itself.  I suggest:
IN CASE OF EMERGENCY - This CD will help you connect to other wireless devices
1.  Insert CD into wireless laptop
2.  Reboot the laptop (please wait patiently as booting takes a while)
3.  Click the "Configuring Your Mesh Node" icon on the desktop for further directions
NOTE:  no files on you laptop will be harmed by this.

**Comment by virtadpt** [comment]
That obvious place should probably be on the desktop after the node boots up.  It should probably be HTML so the user can double-click on the icon, which will start Firefox.

For later releases of the CD (as well as any disk label images we release) that is probably a good idea.  It would certainly be ideal for working with disaster response organizations.

**Comment by virtadpt** [comment]
Closing - nodes are configured automagickally at boot-time, and everything that users need runs at boot-time.
