### ISSUE TITLE
How reliably can clients connect to a mesh node?

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#91]
Some of the user feedback we got from last weekend is that some OSes seem to have trouble connecting to mesh nodes.  From Gary Mulder:

-The laptops were all sitting next to each other and we were using a channel which was not being used by any other APs.
-Windows 7 and Windows XP had would take a long time (minutes) before it was working, then disconnect after a while.
-An Ubuntu netbook WiFi client seems to be a bit more reliable.
-An HTC Desire couldn't see the ad hoc network
-An iPhone 4 did seem to work.

It would behoove us to test as many clients as possible to see how they act.  If there is anything we can change on our end to make client associations more reliable, we need to know what it is and make it happen.

Windows on the client side is more common than Linux on the client side, so starting there seems like a good idea.

**Comment by virtadpt** [comment]
The final two questions in the dnsmasq FAQ are illuminating:

http://www.thekelleys.org.uk/dnsmasq/docs/FAQ

**Comment by virtadpt** [comment]
E-mailed Gary Mulder to keep him in the loop with respect to his user feedback.

**Comment by ghost** [comment]
I'd be happy to test any new configs. I have a few laptops that can be used variously as mesh nodes or Windows clients, and various smart phones as clients. I'd need a bootable .iso to use the laptops, however.

**Comment by virtadpt** [comment]
We can make a v0.2a test image available for testing.  It'll be a good test of the global construction script.

**Comment by virtadpt** [comment]
This is going to be a work in progress; the most client devices we test with Byzantium, the most this is going to change.  I don't think this should be a ticket in the bug tracker so much as it should go in the HCL under "Here's what we know works" or "Here's what we know doesn't work."  It's certainly going to be an ongoing discussion on the mailing list.

**Comment by Sitwon** [comment]
https://github.com/Byzantium/Byzantium/wiki/HCL
