### ISSUE TITLE
Wireless network emulation for testing.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#92]
It's been suggested that we find a way to emulate large wireless networks somehow to stress-test the scalability of Byzantium-style meshes.  We could do that with a large number of virtual machines on a single broadcast domain  but we'd need a way of exposing all of the wireless interfaces on the underlying hardware to the VMs.

A wireless emulation layer has been suggested as well.

https://cs.cmu.edu/~emulator/

https://www.opnet.com/solutions/network_rd/modeler_wireless.html

http://www.icir.org/models/simulators.html

http://www.openwns.org/Wiki

http://www.awe-communications.com/Network/MESH/index.html

http://wirelessafrica.meraka.org.za/wiki/index.php/Wireless_Mesh_Networking#Network_Simulation

We could also do it the hard way, with multiple physical 802.11 interfaces, multiple virtual machines (with one wireless interface assigned to each), USB hubs and extension cables to get some transceiver dispersion, and multiple physical virtualization servers.  However, that's not going to get us a very large mesh to stress-test.

**Comment by virtadpt** [comment]
The last question in this FAQ is relevant to this ticket: http://www.pps.jussieu.fr/~jch/software/babel/faq.html

**Comment by ag4ve** [comment]
my first thought here is using tcpreplay and a bunch of pcap files. per the pcap files:
http://sourceforge.net/apps/mediawiki/networkminer/index.php?title=Publicly_available_PCAP_files

**Comment by virtadpt** [comment]
I know that there are people who emulate mesh networks with either wired networks or virtual machine networks and IP tables, but I don't know how, exactly they go about this (not being an IP tables expert by any stretch).  It would be worth investigating, however.

**Comment by Sitwon** [comment]
This seems outside the scope of our project. Testing the scalability of the underlying routing protocols is best left to the authors of those protocols.

**Comment by ag4ve** [comment]
Either way, a test suite should accompany any scripts. I don't know of a
way of proceeding with that without some way of testing the protocols. If
we can do some tcpreplay, that's fine or if it requires more logic.

I agree the protocol authors should write the tests but we need to make
sure they are being used and pass.
